const number = { type: 'number' }, string = { type: 'string' };
const browserKeyframe = { type: 'object', properties: { time:number, content:string, amplitude:number, speed:number, x:number, y:number, z:number, offset:number, scrollY:number, rotate:{type:'boolean'} }, required:['time','content'] };
const zoomKeyframe = { type:'object', properties:{ time:number, selector:string, x:number, y:number, scale:number, speed:number, duration:number, easing:string, curve:string }, required:['time','scale','easing'] };
const cursorStep = { type:'object', properties:{ time:number, selector:string, duration:number, action:string, click:{type:'boolean'}, clickDuration:number, hideAfterClick:{type:'boolean'} }, required:['time','selector','duration'] };
const morphBox = { type:'object', properties:{ holdFrames:number, morphSpeed:number }, required:['holdFrames','morphSpeed'] };
const textKeyframe = { type:'object', properties:{ time:number, opacity:number, scale:number }, required:['time','opacity','scale'] };
const ringKeyframe = { type:'object', properties:{ time:number, speed:number, radius:number, tiltX:number, tiltZ:number, textDepth:number, easing:string }, required:['time','speed','radius','tiltX','tiltZ','textDepth','easing'] };
const haloMoveKeyframe = { type:'object', properties:{ time:number, x:number, y:number, z:number, easing:string }, required:['time','x','y','z','easing'] };
const cardZoomKeyframe = { type:'object', properties:{ time:number, focusCard:number, zoomOut:{type:'boolean'}, x:number, y:number, easing:string }, required:['time','focusCard','zoomOut','x','y','easing'] };
const device3DKeyframe = { type:'object', properties:{ time:number, x:number, y:number, z:number, rotateX:number, rotateY:number, rotateZ:number, scale:number, easing:string, curve:string }, required:['time','x','y','z','rotateX','rotateY','rotateZ','scale','easing'] };
const camera3DKeyframe = { type:'object', properties:{ time:number, x:number, y:number, z:number, rotateX:number, rotateY:number, rotateZ:number, fov:number, easing:string, curve:string }, required:['time','x','y','z','rotateX','rotateY','rotateZ','fov','easing'] };
const text3DKeyframe = { type:'object', properties:{ time:number, x:number, y:number, scale:number, opacity:number, easing:string, curve:string }, required:['time','x','y','scale','opacity','easing'] };
const deviceText = { type:'object', properties:{ content:string, fontSize:string, fontWeight:number, fontFamily:string, color:string, left:string, zIndex:string, keyframes:{type:'array',items:text3DKeyframe} }, required:['content','fontSize','fontWeight','fontFamily','color','left','zIndex','keyframes'] };
const cutSide = { type:'object', properties:{ duration:number, distance:number, drift:number, driftDuration:number, curve:string, ratio:string, opacity:number, scale:number, easing:string, direction:string } };
const videoMedia = { type:'object', properties:{ url:string, type:string, name:string } };
const browserStat = { type:'object', properties:{ label:string, value:string, trend:string } };
const browserCard = { type:'object', properties:{ title:string, body:string, description:string, badge:string, progress:number, url:string } };
const browserResult = { type:'object', properties:{ title:string, url:string, description:string, badge:string } };
const cameraKeyframe = { type:'object', properties:{ time:number, panX:number, panY:number, depth:number, scale:number, rotateX:number, rotateY:number, rotateZ:number, originX:number, originY:number } };
const matchCut = { type:'object', properties:{ enabled:{type:'boolean'}, direction:string, outgoing:cutSide, incoming:cutSide }, required:['enabled','direction','outgoing','incoming'] };

export const etaAdvancedSchema = { type:'object', properties:{
  subtitle:string, searchText:string, url:string, pageTitle:string, pageSubtitle:string, ctaLabel:string, brandMark:string, browserRows:{type:'array',items:string}, videoMedia, videoObjectFit:string,
  browserLayout:string, browserSearchPlaceholder:string, browserNavItems:{type:'array',items:string}, browserStats:{type:'array',items:browserStat}, browserCards:{type:'array',items:browserCard}, browserResults:{type:'array',items:browserResult}, browserChartValues:{type:'array',items:number}, browserTableColumns:{type:'array',items:string}, browserTableRows:{type:'array',items:{type:'array',items:string}}, cameraKeyframes:{type:'array',items:cameraKeyframe},
  browserKeyframes:{type:'array',items:browserKeyframe}, zoomKeyframes:{type:'array',items:zoomKeyframe}, cursorSteps:{type:'array',items:cursorStep}, textKeyframes:{type:'array',items:textKeyframe}, ringKeyframes:{type:'array',items:ringKeyframe}, haloMoveKeyframes:{type:'array',items:haloMoveKeyframe}, cardZoomKeyframes:{type:'array',items:cardZoomKeyframe}, matchCut,
  animatedBorder:{type:'boolean'}, showShell:{type:'boolean'}, backgroundColor:string, boxShadow:string, pillBackground:string, pillTextColor:string,
  autoMotionEnabled:{type:'boolean'}, autoMotionPreset:string, autoMotionIntensity:number, autoTransformKeyframes:{type:'array',items:device3DKeyframe},
  textContent:string, fontSize:string, fontWeight:number, fontFamily:string, textColor:string, zIndex:number, textLeft:number, framesPerCharacter:number, typingStartFrame:number, pillStartFrame:number, pillEndFrame:number, searchBackground:string,
  cursorDelay:number, cursorMoveDuration:number, cursorClickDuration:number, cursorClick:{type:'boolean'}, cursorStartX:number, cursorStartY:number, cursorEndX:number, cursorEndY:number, cursorSize:number, morphBoxes:{type:'array',items:morphBox},
  typingSpeed:number, entranceStartScale:number, entranceEndScale:number, entranceStiffness:number, entranceDamping:number,
  logoText:string, logoImageUrl:string, logoBackground:string, circleColor:string, logoMotionStyle:string, logoFontSize:number, logoFontWeight:number, logoIconSize:number, logoScale:number, logoGap:number, circleRadius:number, slideOffset:number, circleStart:number, circleEnd:number, iconScaleStart:number, iconScaleEnd:number, logoSlideStart:number, logoSlideEnd:number, textStartFrame:number, letterStagger:number, revealDuration:number, logoSlideDistance:number, blurStart:number, blurEnd:number, logoScaleStart:number, logoScaleEnd:number, logoShiftStart:number, logoShiftEnd:number, textSlideDuration:number, textSlideDistance:number,
  phoneModel:string, phoneCount:number, deviceColor:string, lightStrength:number, phoneKeyframes:{type:'array',items:device3DKeyframe}, macbookKeyframes:{type:'array',items:device3DKeyframe}, cameraKeyframes:{type:'array',items:camera3DKeyframe}, deviceTexts:{type:'array',items:deviceText}, openingEnabled:{type:'boolean'}, openingStart:number, openingSpeed:number,
  centerHeadline:string, cardColor:string, cardFont:string, cardFontSize:number, cardFontWeight:number, cardTextDepth:number, cardRadius:number, cardWidth:number, cardHeight:number, textTransform:string,
  spinPeriodFrames:number, spinSpeed:number, sphereRadius:number, sphereTiltX:number, sphereTiltZ:number, headlineOrbitRadius:number, headlineOrbitSpeed:number, headlineOrbitIncline:number, spinDirection:string, cardPerspective:number, satelliteX:number, satelliteY:number, satelliteZ:number, satelliteRotateX:number, satelliteRotateY:number, satelliteRotateZ:number, spinPhase:number,
  haloX:number, haloY:number, haloZ:number, depthStrength:number, maxBlur:number, centerTextColor:string, centerDriftStrength:number, centerDriftMin:number, centerDriftMax:number, haloBaseX:number, haloBaseY:number, haloBaseZ:number, floatRotation:number, floatSpeed:number
} };