export function buildETAComponentRules(components) {
  return `AVAILABLE ETA COMPONENTS
Choose only from: ${components.join(', ')}.
TitleCard: concise opening, chapter, statement, or payoff. NumberDisplay: metrics and proof. Glass: layered premium depth. BrowserWindow: websites, dashboards, web workflows. PhoneWindow: simple mobile demos. IPhoneAnimated: cinematic 3D phone and camera choreography. MacBookAnimated: cinematic laptop, lid, camera, and screen choreography. Cards: clean collections. Cards2: energetic spatial cards. Cards3: halo depth and center drift. Cards4: camera focus and zoom-out cards. DivMorph: structural geometric transformation. SearchAnimation/SearchAnimation1: expanding typed search with cursor and zoom. SearchAnimation2: spring search entrance with typing and cursor. LogoAnimation/LogoAnimation1: circle, icon, slide, and letters. LogoAnimation2: blur, scale, shift, and text slide. UIAnimation: dashboard/interface assembly with selector zoom. Video: supplied footage only.

COMPONENT AUTO-FILL
BrowserWindow: generate and use the actual web UI as browserHtml: one complete <!DOCTYPE html> document with semantic HTML and inline CSS. If USER_INTENT contains HTML, preserve its text, structure, styles, colors, spacing, dimensions, and visual hierarchy faithfully; do not summarize it or rebuild it as generic cards. If only a product description exists, author a polished complete document from the intent. Set browserViewportWidth and browserViewportHeight from the source viewport or use 1400 × 895, and keep the document self-contained: no markdown fences, scripts, CSS animations, timers, or runtime randomness. Also fill url, pageTitle, pageSubtitle, ctaLabel, brandMark and the structured browser fields as editable fallback data. Fill 2–4 browserKeyframes, 3–5 cameraKeyframes spanning the complete scene, 1–3 zoomKeyframes, and 1–3 cursorSteps targeting selectors that exist in browserHtml. Camera keyframes must use a polished PRODUCT DEMO style with time, panX, panY, depth, scale, rotateX, rotateY, rotateZ, originX, and originY. Keep the browser front-facing with rotation normally 0; use restrained pan, controlled 1.15–1.35 focus punch-ins, and a stable scale 1.0 finish. Never use floating, orbiting, wobbling, or continuous 3D rotation. Browser keyframes contain time, content, amplitude, speed, x, y, z, offset, scrollY, and rotate.
PhoneWindow: turn the scene's natural-language intent into a bespoke, production-quality mobile interface—not a generic feature-card template. Fill phoneHtml with one complete semantic HTML document whose CSS is self-contained and scoped beneath .eta-phone-ui. Design the actual app screen the brief implies (messages, booking, commerce, dashboard, social feed, player, onboarding, maps, finance, or another fitting interface), with realistic content, strong hierarchy, safe-area spacing, and no placeholder copy. Mark 4–6 meaningful elements in reveal order using data-eta-step="1" through data-eta-step="6"; ETA drives those reveals from the video frame, so never add CSS animations, transitions, scripts, timers, or randomness. Use a 393 × 852 mobile viewport, keep all content inside it without clipping, and prefer authentic app UI over a miniature marketing page. If supplied screen media exists, use it instead of phoneHtml. Also fill phoneModel, phoneCount, deviceColor, lightStrength, phoneUiVariant, phoneEyebrow, ctaLabel, exactly 2 concise phoneFeatureCards as editable fallback data, and phoneHyperframes. Use autoMotionPreset float with restrained autoMotionIntensity 0.4–0.6 so the device stays readable.
IPhoneAnimated: fill phoneModel, phoneCount, deviceColor, lightStrength, 2–4 phoneKeyframes, 1–3 cameraKeyframes, 1–3 deviceTexts with keyframes, supplied screen media, and Match Cut. Device keyframes contain time, x/y/z, rotateX/Y/Z, scale, easing, curve. Camera frames contain time, x/y/z, rotateX/Y/Z, fov, easing, curve. Static media always receives pan, zoom, orbit, or parallax.
MacBookAnimated: fill openingEnabled/start/speed, deviceColor, lightStrength, 2–4 macbookKeyframes, 1–3 cameraKeyframes, deviceTexts, supplied screen media, and Match Cut. Coordinate lid, camera, and text.
Cards: fill centerHeadline, cardColor, cardFont/Size/Weight, cardTextDepth, cardRadius/Width/Height, textTransform, and 2–4 ringKeyframes. Ring frames contain time, speed, radius, tiltX, tiltZ, textDepth, easing.
Cards2: fill all Cards values plus spinPeriodFrames, spinSpeed, sphereRadius, sphereTiltX/Z, headlineOrbitRadius/speed/incline, spinDirection, cardPerspective, satelliteX/Y/Z, satelliteRotateX/Y/Z, and spinPhase.
Cards3: fill card dimensions/perspective, haloX/Y/Z, depthStrength, maxBlur, centerHeadline, centerTextColor, card typography, centerDriftStrength/Min/Max, haloBaseX/Y/Z, and 2–4 haloMoveKeyframes with time, x/y/z, easing. Do not add browser zoom frames.
Cards4: fill card and halo values, floatRotation, floatSpeed, and 2–4 cardZoomKeyframes with time, focusCard, zoomOut, x/y, easing; alternate focused and wide states.
DivMorph: fill 2–5 morphBoxes with holdFrames and morphSpeed, 3–5 zoomKeyframes, and 1–3 cursorSteps when interactive.
SearchAnimation/SearchAnimation1: fill searchText, typingStartFrame, framesPerCharacter, pillStartFrame/endFrame, searchBackground, cursor delay/move/click timing, click state, start/end coordinates, size, 3 zoomKeyframes, and 2 cursorSteps targeting .search-text. Use a wide → .search-bar focus → wide camera path scaled to duration.
SearchAnimation2: fill searchText, typingSpeed, entranceStartScale/EndScale/Stiffness/Damping, all cursor values, 3 zoomKeyframes, and 2 cursorSteps. Use coherent spring values and settle before exit.
LogoAnimation/LogoAnimation1: fill logoText, supplied logo URL only, background/text/circle colors, typography, icon size, scale, gap, circle radius, slide offset, circle/icon/slide timing, textStartFrame, letterStagger, revealDuration, and logoSlideDistance. Fit reveal inside duration.
LogoAnimation2: fill logo text/media, deterministic motion style, colors, typography, icon/layout, blur/scale/shift timing, textStartFrame, textSlideDuration, and textSlideDistance.
UIAnimation: fill pageTitle, pageSubtitle, ctaLabel, browserRows, and zoomKeyframes. Use wide at 0, .main-panel focus near 0.8 seconds, and wide near 2 seconds, proportionally scaled for short scenes; include x/y, scale, speed, duration, easing, and curve.
Video: fill videoMedia only from supplied accessible media and videoObjectFit as cover, contain, or fill. Use cover for cinematic footage, contain to preserve the full frame, and fill only when stretching is acceptable. Never invent media URLs; choose another component if no video exists.

All component Match Cuts use 0.25-second outgoing and 0.5-second incoming defaults unless continuity demands a valid intentional adjustment.`;
}