// FlagSense — scenario library & category model.
// Every scenario follows one schema so hundreds more can be added later:
// id, category, title, scenario, green_behavior, yellow_behavior, red_behavior,
// why_it_matters, feelings, healthier_alternative, example_phrase,
// reflection_question, difficulty, safety, tags

import {
  MessageCircle, Flame, ShieldCheck, BrickWall, Eye, HeartHandshake, HandHeart,
  Wind, Ear, Scale, Smartphone, Wallet, Anchor, DoorOpen, Sun, Hand, Bird, CalendarHeart,
} from "lucide-react";

export const CATEGORIES = [
  { id: "communication", label: "Communication", icon: MessageCircle },
  { id: "conflict", label: "Arguments & Conflict", icon: Flame },
  { id: "trust", label: "Trust", icon: ShieldCheck },
  { id: "boundaries", label: "Boundaries", icon: BrickWall },
  { id: "jealousy", label: "Jealousy", icon: Eye },
  { id: "support", label: "Emotional Support", icon: HeartHandshake },
  { id: "apologies", label: "Apologies", icon: HandHeart },
  { id: "space", label: "Personal Space", icon: Wind },
  { id: "listening", label: "Listening", icon: Ear },
  { id: "respect", label: "Respect & Accountability", icon: Scale },
  { id: "social", label: "Social Media", icon: Smartphone },
  { id: "money", label: "Money", icon: Wallet },
  { id: "commitment", label: "Commitment", icon: Anchor },
  { id: "availability", label: "Emotional Availability", icon: DoorOpen },
  { id: "control", label: "Controlling Behavior", icon: Hand },
  { id: "independence", label: "Healthy Independence", icon: Bird },
  { id: "forgiveness", label: "Forgiveness", icon: Sun },
  { id: "dating", label: "Dating", icon: CalendarHeart },
];

export const FEELING_OPTIONS = ["Hurt", "Ignored", "Safe", "Confused", "Respected", "Pressured", "Understood", "Anxious"];
export const PAUSE_FEELINGS = ["Angry", "Hurt", "Jealous", "Afraid", "Ignored", "Frustrated", "Confused"];
export const PAUSE_NEEDS = ["Space", "Reassurance", "Answers", "An apology", "Understanding", "A conversation"];

export const SCENARIOS = [
  {
    id: "space-after-argument",
    category: "space",
    title: "30 minutes alone",
    scenario: "Your partner says they need 30 minutes alone after an argument.",
    green_behavior: "I respect their space and ask when we can talk again.",
    yellow_behavior: "I give them space but become anxious and repeatedly text them.",
    red_behavior: "I accuse them of ignoring me and keep demanding an answer.",
    why_it_matters: "Taking a short break during conflict can be healthy — when both people know the conversation will continue.",
    feelings: ["Respected", "Safe", "Pressured"],
    healthier_alternative: "Give the space, and name when you'll reconnect so neither of you is left in silence.",
    example_phrase: "I need a little time to calm down. I still want to talk about this. Can we talk in 30 minutes?",
    reflection_question: "How might your partner feel if you repeatedly contacted them after they asked for space?",
    difficulty: "everyday",
    tags: ["conflict", "space", "repair"],
  },
  {
    id: "text-answered-late",
    category: "jealousy",
    title: "The unanswered text",
    scenario: "Your partner hasn't replied to your message for several hours while out with friends.",
    green_behavior: "I assume they're busy and go on with my day.",
    yellow_behavior: "I send a few follow-up texts and feel uneasy until they answer.",
    red_behavior: "I call repeatedly, get angry, and demand to know who they're with.",
    why_it_matters: "Silence usually means distraction, not rejection. Reacting to it as rejection can turn a neutral moment into a conflict.",
    feelings: ["Pressured", "Anxious", "Respected"],
    healthier_alternative: "Sit with the discomfort before acting on it. Ask yourself what story you're telling about the silence.",
    example_phrase: "No rush on a reply — just thinking of you. Tell me about your night when you're free.",
    reflection_question: "What did the unanswered message mean to you before you decided what it meant about them?",
    difficulty: "everyday",
    tags: ["jealousy", "trust", "anxiety"],
  },
  {
    id: "silent-treatment",
    category: "conflict",
    title: "The silent treatment",
    scenario: "You're hurt and upset, and your partner asks what's wrong.",
    green_behavior: "I say I'm hurt and need a moment, then come back to talk.",
    yellow_behavior: "I say 'nothing' but my tone and body language say otherwise.",
    red_behavior: "I shut down completely and refuse to speak for days.",
    why_it_matters: "The other person may not know whether you need space or are intentionally punishing them.",
    feelings: ["Confused", "Ignored", "Anxious"],
    healthier_alternative: "Name that you need a pause — and when you'll return. Silence with a return time is space; silence without one can feel like punishment.",
    example_phrase: "I'm overwhelmed right now. I need some time to cool down, but I want to finish this conversation later.",
    reflection_question: "Is your silence protecting you, or punishing them?",
    difficulty: "hard",
    tags: ["conflict", "space", "stonewalling"],
  },
  {
    id: "partner-news",
    category: "support",
    title: "Big news, bad timing",
    scenario: "Your partner excitedly shares big news, right as you walk in exhausted from a long day.",
    green_behavior: "I set it down for a second and celebrate with them, even briefly.",
    yellow_behavior: "I half-listen while checking my phone.",
    red_behavior: "I say 'not now' and change the subject to my own day.",
    why_it_matters: "How we respond to good news matters as much as how we handle bad news. Missed excitement can feel like missed love.",
    feelings: ["Ignored", "Hurt", "Understood"],
    healthier_alternative: "If you can't be fully present, say so honestly and commit to a time — then actually follow through.",
    example_phrase: "I genuinely want to hear this properly. Give me 20 minutes to decompress and it's all yours.",
    reflection_question: "When was the last time someone celebrated your good news — or didn't?",
    difficulty: "everyday",
    tags: ["support", "presence", "joy"],
  },
  {
    id: "bad-apology",
    category: "apologies",
    title: "The 'I'm sorry you feel that way'",
    scenario: "You hurt your partner's feelings, and they tell you so.",
    green_behavior: "I apologize for what I did and ask how it landed for them.",
    yellow_behavior: "I apologize, but I add an explanation that softens my part.",
    red_behavior: "I say 'I'm sorry you feel that way' and point out what they did first.",
    why_it_matters: "An apology that explains your intent before their hurt can feel like a defense, not a repair.",
    feelings: ["Hurt", "Ignored", "Respected"],
    healthier_alternative: "Apologize for the impact first. Explanation can come later — after the repair, not instead of it.",
    example_phrase: "I'm sorry for what I said. It wasn't fair to you. How did it make you feel?",
    reflection_question: "In your apology, whose comfort comes first — yours or theirs?",
    difficulty: "everyday",
    tags: ["apology", "accountability", "repair"],
  },
  {
    id: "phone-on-date",
    category: "social",
    title: "Phone at the table",
    scenario: "You're at dinner together and your partner keeps scrolling their phone.",
    green_behavior: "I gently say I miss them and suggest phones away for a bit.",
    yellow_behavior: "I say nothing but go quiet and cold for the rest of the evening.",
    red_behavior: "I grab the phone or make a sarcastic scene about it.",
    why_it_matters: "Withdrawal can hurt a relationship as much as confrontation — the problem just goes unnamed.",
    feelings: ["Ignored", "Confused", "Understood"],
    healthier_alternative: "Ask for what you want directly, without punishing. A small honest ask beats silent resentment.",
    example_phrase: "I miss you tonight. Could we put the phones away for this dinner?",
    reflection_question: "What do you do when you feel ignored — ask, or quietly pull away?",
    difficulty: "gentle",
    tags: ["social-media", "presence", "repair"],
  },
  {
    id: "checking-phone",
    category: "control",
    title: "Just checking",
    scenario: "You feel insecure and want to look through your partner's phone to feel better.",
    green_behavior: "I notice the insecurity and talk about it instead of acting on it.",
    yellow_behavior: "I glance at their screen whenever a notification appears.",
    red_behavior: "I go through their messages when they're not looking.",
    why_it_matters: "Surveillance doesn't create safety — it replaces it. If trust needs constant proof, the real issue is worth naming.",
    feelings: ["Pressured", "Unsafe", "Anxious"],
    healthier_alternative: "Say the insecurity out loud. 'I'm feeling unsure and I'd rather tell you than check on you.'",
    example_phrase: "I've been feeling insecure lately. Can I talk to you about it instead of letting it turn into suspicion?",
    reflection_question: "Would checking give you peace — or just a shorter list of things to worry about?",
    difficulty: "hard",
    safety: true,
    tags: ["control", "trust", "privacy"],
  },
  {
    id: "friend-boundary",
    category: "boundaries",
    title: "The friend they don't like",
    scenario: "Your partner dislikes one of your close friends and asks you to stop seeing them.",
    green_behavior: "I hear their concern and look for what's really underneath it.",
    yellow_behavior: "I secretly keep seeing the friend to avoid the argument.",
    red_behavior: "I cut off the friend entirely to keep the peace.",
    why_it_matters: "Healthy relationships make room for each person's people. Losing your friendships to avoid conflict is a real cost.",
    feelings: ["Pressured", "Confused", "Respected"],
    healthier_alternative: "Get specific. Is it this friend, or the time spent? A concern you can name is a problem you can solve together.",
    example_phrase: "Help me understand what bothers you — is it her, or how much time I'm away?",
    reflection_question: "Are you keeping the peace, or shrinking your life to fit?",
    difficulty: "hard",
    safety: true,
    tags: ["boundaries", "friends", "control"],
  },
  {
    id: "interrupting-story",
    category: "listening",
    title: "The interruption",
    scenario: "Your partner is telling a long story and you already know where it's going.",
    green_behavior: "I let them finish and respond to how it felt for them.",
    yellow_behavior: "I finish their sentence for them to show I'm following.",
    red_behavior: "I interrupt: 'yes, I know, get to the point.'",
    why_it_matters: "Being listened to is one of the closest things to being loved. The point is rarely the point.",
    feelings: ["Ignored", "Hurt", "Understood"],
    healthier_alternative: "Sit with the suspense. Ask one more question instead of taking the ending away.",
    example_phrase: "And then what happened? I want the whole thing.",
    reflection_question: "Do you listen to reply — or listen to understand?",
    difficulty: "gentle",
    tags: ["listening", "presence", "patience"],
  },
  {
    id: "money-secret",
    category: "money",
    title: "The quiet purchase",
    scenario: "You made a big purchase and you're deciding whether to tell your partner.",
    green_behavior: "I tell them openly, even though the conversation might be uncomfortable.",
    yellow_behavior: "I mention it casually later, downplaying the amount.",
    red_behavior: "I hide it and hope it never comes up.",
    why_it_matters: "Financial honesty is trust in numbers. Hidden money usually costs more than the price tag.",
    feelings: ["Confused", "Respected", "Pressured"],
    healthier_alternative: "Bring it up early and own it fully. Transparency after the fact still rebuilds; discovery never does.",
    example_phrase: "I spent more than I planned on this. I want to be upfront with you about it.",
    reflection_question: "What made honesty feel more expensive than the purchase?",
    difficulty: "everyday",
    tags: ["money", "honesty", "trust"],
  },
  {
    id: "meeting-family",
    category: "commitment",
    title: "Meeting the family",
    scenario: "Your partner invites you to a family event; you're not sure you're ready.",
    green_behavior: "I share honestly what I'm nervous about and we find a pace together.",
    yellow_behavior: "I agree, then act distant and withdrawn at the event.",
    red_behavior: "I cancel last minute with a vague excuse.",
    why_it_matters: "Mixed signals about milestones can hurt more than a no. Uncertainty, said out loud, is still care.",
    feelings: ["Confused", "Hurt", "Respected"],
    healthier_alternative: "Say where you actually are. 'I'm not ready yet' is easier to work with than a yes that behaves like a no.",
    example_phrase: "I care about you, and I want to meet them — I'd just like a bit more time first. Can we plan it for next month?",
    reflection_question: "Did you communicate your hesitation — or just your absence?",
    difficulty: "everyday",
    tags: ["commitment", "milestones", "honesty"],
  },
  {
    id: "hard-day-partner",
    category: "availability",
    title: "Both tired",
    scenario: "You've had a hard day. Your partner starts telling you about their hard day.",
    green_behavior: "I say I'm running low, and ask if we can talk after a short rest.",
    yellow_behavior: "I listen while visibly distracted and keep looking away.",
    red_behavior: "I say 'my day was worse' and take over the conversation.",
    why_it_matters: "Support isn't a competition. Two tired people can still choose tenderness — or at least honesty about their limits.",
    feelings: ["Ignored", "Hurt", "Understood"],
    healthier_alternative: "Name your capacity instead of letting your body say it for you. A rain check you honor beats half-attention.",
    example_phrase: "My tank is empty tonight. Your day matters to me — can we do this properly after a rest?",
    reflection_question: "When you're depleted, do you ask for care — or just stop giving it?",
    difficulty: "everyday",
    tags: ["support", "capacity", "honesty"],
  },
  {
    id: "owning-mistake",
    category: "respect",
    title: "Called out",
    scenario: "Your partner points out, calmly, that something you said hurt them.",
    green_behavior: "I take it in, thank them, and look at my part.",
    yellow_behavior: "I accept it but quickly remind them of their past mistakes.",
    red_behavior: "I turn it around: 'you're too sensitive.'",
    why_it_matters: "How you receive feedback decides how honest people can be with you. Defensiveness teaches others to stay quiet.",
    feelings: ["Hurt", "Safe", "Pressured"],
    healthier_alternative: "Separate the message from the messenger. Even if delivery stung, the content may still be worth hearing.",
    example_phrase: "That's hard to hear, but I'm glad you told me. Give me a minute to sit with it.",
    reflection_question: "Can you hear something true about yourself without it becoming an attack?",
    difficulty: "hard",
    tags: ["accountability", "feedback", "defensiveness"],
  },
  {
    id: "solo-trip",
    category: "independence",
    title: "The solo trip",
    scenario: "Your partner tells you they're planning a weekend trip with friends.",
    green_behavior: "I'm happy for them and ask to hear about the plan.",
    yellow_behavior: "I say it's fine, but go cold for the rest of the week.",
    red_behavior: "I guilt them about leaving me and make them feel selfish.",
    why_it_matters: "Two whole people make one healthy relationship. Independence isn't distance — it's what makes coming back a choice.",
    feelings: ["Respected", "Confused", "Pressured"],
    healthier_alternative: "If it stings, say the sting — not the verdict. 'I'll miss you' and 'you shouldn't go' are very different sentences.",
    example_phrase: "I'll miss you — go have an amazing time. Tell me everything when you're back.",
    reflection_question: "Does their independence feel like freedom for both of you, or a threat?",
    difficulty: "everyday",
    tags: ["independence", "jealousy", "space"],
  },
  {
    id: "grudge",
    category: "forgiveness",
    title: "The old wound",
    scenario: "A past mistake of your partner's comes up in an argument — again.",
    green_behavior: "I notice the pattern and suggest we deal with the wound properly, once.",
    yellow_behavior: "I bring it up whenever I'm losing the current argument.",
    red_behavior: "I keep a list and use it as a weapon in every conflict.",
    why_it_matters: "Unresolved hurt doesn't disappear — it invoices. A wound that's used as ammunition never gets to heal.",
    feelings: ["Hurt", "Pressured", "Anxious"],
    healthier_alternative: "If it keeps resurfacing, it needs a real conversation of its own — not a cameo in every fight.",
    example_phrase: "I keep bringing that up, and that's not fair. I think it still hurts. Can we actually deal with it?",
    reflection_question: "Are you holding a grudge, or is something genuinely unresolved?",
    difficulty: "hard",
    tags: ["forgiveness", "conflict", "repair"],
  },
  {
    id: "third-date-honesty",
    category: "dating",
    title: "Not feeling it yet",
    scenario: "You've been on a few dates. They're clearly more interested than you are.",
    green_behavior: "I'm honest about where I am, kindly and soon.",
    yellow_behavior: "I keep things ambiguous so I don't lose the attention.",
    red_behavior: "I stay for the company while knowing I'll eventually leave.",
    why_it_matters: "Ambiguity costs the other person time and hope. Honest disinterest is kinder than warm uncertainty.",
    feelings: ["Confused", "Respected", "Hurt"],
    healthier_alternative: "Choose clarity over comfort. You can't control their feelings — you can only stop managing them.",
    example_phrase: "I've really enjoyed this, and I want to be honest: I don't feel the same spark yet. I wanted you to know rather than drift.",
    reflection_question: "Are you being honest about your interest — or just avoiding the discomfort of theirs?",
    difficulty: "everyday",
    tags: ["dating", "honesty", "clarity"],
  },
  {
    id: "trust-after-lateness",
    category: "trust",
    title: "Home late",
    scenario: "Your partner comes home two hours later than they said, phone dead.",
    green_behavior: "I'm glad they're safe and tell them I was worried, without accusing.",
    yellow_behavior: "I interrogate them about every detail of the evening.",
    red_behavior: "I refuse to talk to them for the rest of the night.",
    why_it_matters: "Worry often wears the costume of anger. Naming the worry is how it becomes care instead of conflict.",
    feelings: ["Pressured", "Understood", "Anxious"],
    healthier_alternative: "Lead with the feeling underneath: relief and worry, not investigation and verdict.",
    example_phrase: "When you didn't answer I got scared. I'm glad you're home — next time, even one bar of battery, send me anything.",
    reflection_question: "Was your first question about their safety — or their guilt?",
    difficulty: "everyday",
    tags: ["trust", "worry", "repair"],
  },
  {
    id: "safety-put-downs",
    category: "control",
    title: "Repeated put-downs",
    scenario: "Your partner regularly calls you stupid or worthless, then says they're 'just joking'.",
    green_behavior: "I name that it hurts and set a clear boundary about how I'm spoken to.",
    yellow_behavior: "I laugh along to keep the peace, and feel smaller over time.",
    red_behavior: "I believe it must be my fault and try harder to deserve kindness.",
    why_it_matters: "Contempt is one of the strongest predictors of relationship harm. If 'jokes' consistently leave you smaller, that's not a communication style — it's a pattern worth taking seriously.",
    feelings: ["Hurt", "Pressured", "Safe"],
    healthier_alternative: "Trust how it lands on you, not how it was framed. If it doesn't stop when named clearly, that information matters.",
    example_phrase: "When you call me that, it hurts — even as a joke. I need that to stop.",
    reflection_question: "After time with them, do you feel more or less like yourself?",
    difficulty: "hard",
    safety: true,
    tags: ["contempt", "safety", "respect"],
  },
];

// Growth axes for the progress dashboard — derived from answered scenarios.
export const AXES = [
  { id: "communication", label: "Communication", cats: ["communication", "listening"] },
  { id: "empathy", label: "Empathy", cats: ["support", "apologies", "forgiveness"] },
  { id: "boundaries", label: "Boundaries", cats: ["boundaries", "space", "independence"] },
  { id: "conflict", label: "Conflict", cats: ["conflict", "respect"] },
  { id: "trust", label: "Trust", cats: ["trust", "jealousy", "social", "money", "commitment", "availability", "control", "dating"] },
];

export const AXIS_CHALLENGES = {
  communication: "Next time you're frustrated, explain what you're feeling before explaining what the other person did wrong.",
  empathy: "Ask one more question today before offering your opinion.",
  boundaries: "Say one honest 'no' this week — kindly, and without a paragraph of excuses.",
  conflict: "During your next disagreement, repeat back what they said before you answer it.",
  trust: "When you feel a spike of doubt, name the feeling out loud instead of investigating it.",
};

export const DAILY_LESSONS = [
  { thought: "Taking space isn't the same as avoiding a conversation.", healthy: "I need 30 minutes to calm down. Let's talk afterward.", unhealthy: "I don't want to talk about it." },
  { thought: "A feeling you can name is a feeling you can handle.", healthy: "I'm feeling insecure tonight — can I talk to you about it?", unhealthy: "Fine. Nothing's wrong." },
  { thought: "Listening is not waiting for your turn to speak.", healthy: "Tell me the whole thing — I'm not going anywhere.", unhealthy: "Yeah, yeah — so anyway, what happened to me was…" },
  { thought: "You can be right, or you can be close. Rarely both at once.", healthy: "I might be right, but being close to you matters more right now.", unhealthy: "Admit it — I'm right and you know it." },
  { thought: "An apology that explains first isn't an apology yet.", healthy: "I'm sorry. It wasn't fair to you.", unhealthy: "I'm sorry you feel that way." },
  { thought: "Jealousy is information about you, not evidence about them.", healthy: "I noticed I felt jealous tonight and I want to understand why.", unhealthy: "Who were you texting?" },
  { thought: "The tone is often the message.", healthy: "Can I restart that? It came out sharper than I meant.", unhealthy: "Well excuse me for caring." },
  { thought: "Small bids for attention are how love asks: 'are you there?'", healthy: "I saw you trying to show me that — thank you.", unhealthy: "Can you not see I'm busy?" },
  { thought: "Two tired people can still choose tenderness.", healthy: "My tank is empty — but your day matters. Give me twenty minutes.", unhealthy: "My day was worse, honestly." },
  { thought: "Repair beats perfection — every time.", healthy: "That came out wrong. Let me try again.", unhealthy: "You always take it the wrong way." },
];

// helper used above for the "correct empathy" answer in feeling lists