import React,{useMemo,useState} from 'react';
import {parseTable} from '@/lib/aca/table';
export default function ACAData({aca}) {
  const file=aca.workspace.file,[search,setSearch]=useState(''),[sort,setSort]=useState(''),[filterColumn,setFilterColumn]=useState(''),[filterValue,setFilterValue]=useState(''),[output,setOutput]=useState('/workspace/cleaned_inventory.csv');
  const parsed=useMemo(()=>{try{return file?parseTable(file.text,file.file.path):{columns:[],rows:[]};}catch(e){return {columns:[],rows:[],error:e.message};}},[file?.revision.id]);
  const rows=useMemo(()=>{let list=parsed.rows.filter(r=>r.some(v=>v.toLowerCase().includes(search.toLowerCase())) && (!filterColumn || r[parsed.columns.indexOf(filterColumn)]===filterValue));if(sort){const i=parsed.columns.indexOf(sort);list=[...list].sort((a,b)=>a[i].localeCompare(b[i]));}return list;},[parsed,search,sort,filterColumn,filterValue]);
  const blocked=aca.disabled || !aca.computer.current_session_id;
  const verification=aca.workspace.data.verifications.find(v=>v.output_revision_id===file?.revision.id);
  return <div className="aca-stack" data-aca-target={aca.view.fileId?'file:'+aca.view.fileId:undefined}><div className="aca-row"><select className="aca-input flex-1" value={aca.view.fileId || ''} disabled={blocked} onChange={e=>aca.action('OPEN_FILE',{file_id:e.target.value,app_id:'aca.data'})}><option value="">OPEN CSV / JSON</option>{aca.workspace.data.files.filter(f=>/\.(csv|json)$/.test(f.path)).map(f=><option key={f.id} value={f.id}>{f.path}</option>)}</select><span>{parsed.rows.length} actual records · {rows.length} visible</span></div><div className="aca-row"><input className="aca-input flex-1" placeholder="Search actual rows" value={search} onChange={e=>setSearch(e.target.value)}/><select className="aca-input flex-1" value={sort} onChange={e=>setSort(e.target.value)}><option value="">SORT COLUMN</option>{parsed.columns.map(c=><option key={c}>{c}</option>)}</select><select className="aca-input flex-1" value={filterColumn} onChange={e=>setFilterColumn(e.target.value)}><option value="">FILTER COLUMN</option>{parsed.columns.map(c=><option key={c}>{c}</option>)}</select><input className="aca-input flex-1" placeholder="Exact filter value" value={filterValue} onChange={e=>setFilterValue(e.target.value)}/></div><div className="aca-row"><input className="aca-input flex-1" value={output} onChange={e=>setOutput(e.target.value)}/><button data-aca-target="control:transform" className="aca-btn" disabled={blocked || !file} onClick={()=>aca.action('DATA_TRANSFORM',{file_id:file.file.id,revision_id:file.revision.id,output_path:output,app_id:'aca.data'})}>CLEAN INVENTORY</button><button className="aca-btn" disabled={blocked || !file} onClick={()=>aca.action('EXPORT_DATA',{file_id:file.file.id,output_path:output,search,sort_column:sort,filter_column:filterColumn,filter_value:filterValue,app_id:'aca.data'})}>EXPORT VIEW</button></div><p className="aca-dim">Local deterministic operation · first valid SKU wins · whitespace normalized · SKU uppercase · category lowercase · strict nonnegative prices. 1 SIM COMPUTE per completed action; no tKAS charge.</p>{verification && <div className="aca-notice"><strong className={verification.status==='PASS'?'aca-cyan':'aca-danger'}>{verification.status==='PASS'?'VERIFIED':'VERIFICATION FAILED'}</strong><pre className="aca-pre">{JSON.stringify(verification.summary,null,2)}</pre><p className="break-all">Bound SHA-256: {verification.output_sha256}</p></div>}{parsed.error && <p className="aca-danger">{parsed.error}</p>}<div className="overflow-auto"><table className="aca-table"><thead><tr>{parsed.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,500).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>{rows.length>500 && <p>Showing first 500 rows; export processes all bounded rows.</p>}</div>;
}