import React,{useState} from 'react';
import acaClient from '@/lib/aca/client';
export default function ACAFiles({aca}) {
  const [path,setPath]=useState('/workspace/new.txt'),[text,setText]=useState(''),[destination,setDestination]=useState('/documents/copy.txt'),[downloadError,setDownloadError]=useState('');
  const files=aca.replayId?(aca.view.files || []):aca.workspace.data.files;
  const selected=aca.workspace.file;
  const blocked=aca.disabled || !aca.computer.current_session_id;
  const download=async f=>{try{const r=await acaClient('acaWorkspace',{computer_id:aca.computer.id,mode:'download',file_id:f.id});const link=document.createElement('a');link.href=r.signed_url;link.download=r.filename;link.target='_blank';link.rel='noopener';link.click();}catch(e){setDownloadError(e.message);}};
  return <div className="aca-stack"><div className="aca-row"><input aria-label="New file path" className="aca-input flex-1" value={path} onChange={e=>setPath(e.target.value)}/><button className="aca-btn" disabled={blocked} onClick={()=>aca.action('CREATE_FILE',{path,text,app_id:'aca.files'})}>CREATE FILE</button><button className="aca-btn" disabled={blocked} onClick={()=>aca.action('MKDIR',{path,app_id:'aca.files'})}>MKDIR</button></div><textarea className="aca-input" placeholder="New file content" value={text} onChange={e=>setText(e.target.value)}/><table className="aca-table"><thead><tr><th>PATH</th><th>TYPE</th><th>BYTES</th><th>MODIFIED</th><th/></tr></thead><tbody>{files.map(f=><tr className="aca-file-row" key={f.id} data-aca-target={'file:'+f.id}><td><button className="aca-btn" disabled={blocked || f.kind!=='FILE'} onClick={()=>aca.action('OPEN_FILE',{file_id:f.id,app_id:'aca.files'})}>{f.path}</button></td><td>{f.kind}</td><td>{f.revision?.size_bytes ?? '—'}</td><td>{f.updated_date?new Date(f.updated_date).toLocaleTimeString():'historical'}</td><td>{f.kind==='FILE' && <button className="aca-btn" disabled={!!aca.replayId} onClick={()=>download(f)}>DOWNLOAD</button>}</td></tr>)}</tbody></table>{downloadError && <p className="aca-danger">{downloadError}</p>}{selected && <><h3>SELECTED {selected.file.path}</h3><div className="aca-meta"><span>SHA-256</span><span>{selected.revision.sha256}</span><span>REVISION</span><span>{selected.revision.id}</span></div><pre className="aca-pre max-h-40 overflow-auto">{selected.text}</pre><div className="aca-row"><input className="aca-input flex-1" value={destination} onChange={e=>setDestination(e.target.value)}/>{['COPY_FILE','MOVE_FILE','DELETE_FILE'].map(type=><button key={type} className="aca-btn" disabled={blocked} onClick={()=>aca.action(type,{file_id:selected.file.id,destination,app_id:'aca.files'})}>{type.replace('_FILE','')}</button>)}<button className="aca-btn" disabled={blocked} onClick={()=>aca.action('OPEN_FILE',{file_id:selected.file.id,app_id:'aca.editor'})}>EDIT</button></div><p className="aca-dim">MOVE also renames; files stay inside the authorized workspace.</p></>}</div>;
}