// 150 free, public-domain books on wealth, money, success, character and the economics of prosperity.
// gid = Project Gutenberg id (fetched directly). Entries without gid resolve by title/author search.
const g = (title, author, year, gid, subjects) => ({
  title,
  author,
  year,
  gutenberg_id: gid || "",
  cover: gid ? `https://www.gutenberg.org/cache/epub/${gid}/pg${gid}.cover.medium.jpg` : "",
  subjects: subjects || ["Wealth"],
  source: "search",
  free: true,
});

export const WEALTH_BOOKS = [
  // ---- Money mindset & success classics ----
  g("The Richest Man in Babylon", "George S. Clason", 1926, "", ["Money", "Parables"]),
  g("The Science of Getting Rich", "Wallace D. Wattles", 1910, "", ["Wealth", "Mindset"]),
  g("The Science of Being Great", "Wallace D. Wattles", 1911, "", ["Success", "Mindset"]),
  g("The Science of Being Well", "Wallace D. Wattles", 1910, "", ["Health", "Mindset"]),
  g("As a Man Thinketh", "James Allen", 1903, "4507", ["Mindset", "Character"]),
  g("From Poverty to Power", "James Allen", 1901, "", ["Prosperity", "Mindset"]),
  g("The Path of Prosperity", "James Allen", 1901, "", ["Prosperity"]),
  g("Eight Pillars of Prosperity", "James Allen", 1911, "", ["Prosperity", "Character"]),
  g("The Mastery of Destiny", "James Allen", 1909, "", ["Self-mastery"]),
  g("Byways of Blessedness", "James Allen", 1904, "", ["Mindset"]),
  g("Acres of Diamonds", "Russell H. Conwell", 1890, "368", ["Opportunity", "Wealth"]),
  g("The Art of Money Getting", "P. T. Barnum", 1880, "8581", ["Money", "Business"]),
  g("Struggles and Triumphs", "P. T. Barnum", 1869, "", ["Memoir", "Business"]),
  g("The Master Key System", "Charles F. Haanel", 1912, "", ["Mindset", "Wealth"]),
  g("The Law of Success", "Napoleon Hill", 1928, "", ["Success", "Wealth"]),
  g("The Secret of the Ages", "Robert Collier", 1926, "", ["Mindset", "Wealth"]),
  g("The Power of Concentration", "Theron Q. Dumont", 1918, "", ["Focus", "Success"]),
  g("Your Forces and How to Use Them", "Christian D. Larson", 1912, "", ["Mindset"]),
  g("Thought Vibration", "William Walker Atkinson", 1906, "", ["Mindset"]),
  g("The Secret of Success", "William Walker Atkinson", 1908, "", ["Success"]),
  g("Thoughts Are Things", "Prentice Mulford", 1889, "", ["Mindset"]),
  g("Your Invisible Power", "Genevieve Behrend", 1921, "", ["Mindset", "Visualization"]),
  g("The Edinburgh Lectures on Mental Science", "Thomas Troward", 1904, "", ["Mindset"]),
  g("In Tune with the Infinite", "Ralph Waldo Trine", 1897, "", ["Prosperity", "Spirit"]),
  g("The Game of Life and How to Play It", "Florence Scovel Shinn", 1925, "", ["Prosperity"]),
  g("Dollars Want Me", "Henry Harrison Brown", 1903, "", ["Money", "Mindset"]),
  g("Pushing to the Front", "Orison Swett Marden", 1894, "", ["Success"]),
  g("He Can Who Thinks He Can", "Orison Swett Marden", 1908, "", ["Success"]),
  g("Every Man a King", "Orison Swett Marden", 1906, "", ["Self-mastery"]),
  g("Peace, Power and Plenty", "Orison Swett Marden", 1909, "", ["Prosperity"]),
  g("The Miracle of Right Thought", "Orison Swett Marden", 1910, "", ["Mindset"]),
  g("Self-Help", "Samuel Smiles", 1859, "935", ["Character", "Success"]),
  g("Thrift", "Samuel Smiles", 1875, "", ["Saving", "Character"]),
  g("Character", "Samuel Smiles", 1871, "", ["Character"]),
  g("Duty", "Samuel Smiles", 1880, "", ["Character"]),
  g("Getting On in the World", "William Mathews", 1873, "", ["Success"]),
  g("A Message to Garcia", "Elbert Hubbard", 1899, "", ["Work ethic"]),
  g("How to Live on 24 Hours a Day", "Arnold Bennett", 1908, "2274", ["Time", "Productivity"]),
  g("Mental Efficiency", "Arnold Bennett", 1911, "", ["Productivity"]),
  g("The Human Machine", "Arnold Bennett", 1908, "", ["Self-mastery"]),
  g("The Art of Public Speaking", "Dale Carnegie & J. B. Esenwein", 1915, "16317", ["Communication"]),
  g("The Principles of Scientific Management", "Frederick W. Taylor", 1911, "6435", ["Business", "Management"]),
  g("My Life and Work", "Henry Ford", 1922, "7213", ["Business", "Memoir"]),
  g("Random Reminiscences of Men and Events", "John D. Rockefeller", 1909, "17090", ["Business", "Memoir"]),
  g("Autobiography of Andrew Carnegie", "Andrew Carnegie", 1920, "17976", ["Business", "Memoir"]),
  g("The Empire of Business", "Andrew Carnegie", 1902, "", ["Business"]),
  g("The Gospel of Wealth", "Andrew Carnegie", 1889, "", ["Philanthropy", "Wealth"]),
  g("The Autobiography of Benjamin Franklin", "Benjamin Franklin", 1791, "148", ["Memoir", "Thrift"]),
  g("Poor Richard's Almanack", "Benjamin Franklin", 1732, "", ["Proverbs", "Thrift"]),
  g("Up from Slavery", "Booker T. Washington", 1901, "2376", ["Memoir", "Perseverance"]),
  g("Narrative of the Life of Frederick Douglass", "Frederick Douglass", 1845, "23", ["Memoir", "Freedom"]),
  g("The Education of Henry Adams", "Henry Adams", 1907, "2044", ["Memoir"]),
  g("The Strenuous Life", "Theodore Roosevelt", 1900, "", ["Work ethic"]),
  g("Letters to His Son", "Lord Chesterfield", 1774, "3361", ["Conduct", "Success"]),

  // ---- Economics & markets ----
  g("The Wealth of Nations", "Adam Smith", 1776, "3300", ["Economics"]),
  g("The Theory of Moral Sentiments", "Adam Smith", 1759, "", ["Ethics", "Economics"]),
  g("Principles of Political Economy", "John Stuart Mill", 1848, "", ["Economics"]),
  g("On the Principles of Political Economy and Taxation", "David Ricardo", 1817, "33310", ["Economics"]),
  g("An Essay on the Principle of Population", "Thomas Malthus", 1798, "4239", ["Economics"]),
  g("Lombard Street", "Walter Bagehot", 1873, "4359", ["Banking", "Markets"]),
  g("Extraordinary Popular Delusions and the Madness of Crowds", "Charles Mackay", 1841, "24518", ["Markets", "Bubbles"]),
  g("Reminiscences of a Stock Operator", "Edwin Lefèvre", 1923, "", ["Trading", "Markets"]),
  g("Fifty Years in Wall Street", "Henry Clews", 1908, "", ["Markets", "Memoir"]),
  g("The Theory of the Leisure Class", "Thorstein Veblen", 1899, "833", ["Economics", "Society"]),
  g("Progress and Poverty", "Henry George", 1879, "", ["Economics"]),
  g("The Law", "Frédéric Bastiat", 1850, "", ["Economics", "Liberty"]),
  g("Economic Sophisms", "Frédéric Bastiat", 1845, "", ["Economics"]),
  g("The Economic Consequences of the Peace", "John Maynard Keynes", 1919, "15776", ["Economics"]),
  g("Capital, Volume I", "Karl Marx", 1867, "", ["Economics"]),
  g("The Communist Manifesto", "Karl Marx & Friedrich Engels", 1848, "61", ["Economics", "Politics"]),
  g("Unto This Last", "John Ruskin", 1860, "", ["Economics", "Ethics"]),
  g("Past and Present", "Thomas Carlyle", 1843, "", ["Society", "Work"]),
  g("Looking Backward: 2000–1887", "Edward Bellamy", 1888, "624", ["Utopia", "Economics"]),
  g("Utopia", "Thomas More", 1516, "2130", ["Society"]),
  g("The History of the Standard Oil Company", "Ida Tarbell", 1904, "", ["Business", "History"]),
  g("Wealth Against Commonwealth", "Henry Demarest Lloyd", 1894, "", ["Business", "History"]),
  g("Democracy in America", "Alexis de Tocqueville", 1835, "815", ["Society"]),
  g("Two Treatises of Government", "John Locke", 1689, "7370", ["Property", "Politics"]),
  g("Leviathan", "Thomas Hobbes", 1651, "3207", ["Politics"]),
  g("On Liberty", "John Stuart Mill", 1859, "34901", ["Liberty"]),
  g("Common Sense", "Thomas Paine", 1776, "147", ["Liberty"]),

  // ---- Ancient wisdom on wealth & virtue ----
  g("Meditations", "Marcus Aurelius", 180, "2680", ["Stoicism"]),
  g("The Discourses of Epictetus", "Epictetus", 108, "10661", ["Stoicism"]),
  g("On Benefits", "Seneca", 64, "3794", ["Stoicism", "Generosity"]),
  g("The Consolation of Philosophy", "Boethius", 524, "14328", ["Fortune", "Philosophy"]),
  g("The Economist (Oeconomicus)", "Xenophon", -362, "1173", ["Household", "Economics"]),
  g("Works and Days", "Hesiod", -700, "348", ["Work", "Wisdom"]),
  g("On Duties (De Officiis)", "Cicero", -44, "47001", ["Ethics"]),
  g("Nicomachean Ethics", "Aristotle", -340, "8438", ["Ethics"]),
  g("Politics", "Aristotle", -350, "6762", ["Economics", "Politics"]),
  g("The Republic", "Plato", -375, "1497", ["Philosophy"]),
  g("The Analects", "Confucius", -475, "3330", ["Wisdom"]),
  g("Tao Te Ching", "Lao Tzu", -400, "216", ["Wisdom"]),
  g("The Art of War", "Sun Tzu", -500, "132", ["Strategy"]),
  g("The Bhagavad Gita", "Vyasa", -200, "2388", ["Wisdom", "Duty"]),
  g("The Prince", "Niccolò Machiavelli", 1532, "1232", ["Strategy", "Power"]),
  g("Discourses on Livy", "Niccolò Machiavelli", 1531, "10827", ["Strategy"]),
  g("Essays", "Francis Bacon", 1625, "575", ["Wisdom", "Riches"]),
  g("Essays of Michel de Montaigne", "Michel de Montaigne", 1580, "3600", ["Wisdom"]),
  g("Pensées", "Blaise Pascal", 1670, "18269", ["Wisdom"]),
  g("Essays: First Series", "Ralph Waldo Emerson", 1841, "2944", ["Self-reliance"]),
  g("Essays: Second Series", "Ralph Waldo Emerson", 1844, "16643", ["Wealth", "Character"]),
  g("The Conduct of Life", "Ralph Waldo Emerson", 1860, "", ["Wealth", "Power"]),
  g("Walden", "Henry David Thoreau", 1854, "205", ["Simplicity", "Economy"]),
  g("Civil Disobedience", "Henry David Thoreau", 1849, "71", ["Liberty"]),
  g("Thus Spake Zarathustra", "Friedrich Nietzsche", 1883, "1998", ["Philosophy"]),
  g("Beyond Good and Evil", "Friedrich Nietzsche", 1886, "4363", ["Philosophy"]),
  g("Aesop's Fables", "Aesop", -560, "21", ["Fables", "Wisdom"]),
  g("The Pilgrim's Progress", "John Bunyan", 1678, "131", ["Allegory"]),
  g("The Imitation of Christ", "Thomas à Kempis", 1418, "1653", ["Spirit"]),
  g("Plutarch's Lives", "Plutarch", 100, "674", ["Biography", "Leadership"]),

  // ---- Great novels about money, ambition & fortune ----
  g("The Count of Monte Cristo", "Alexandre Dumas", 1844, "1184", ["Fortune", "Revenge"]),
  g("Great Expectations", "Charles Dickens", 1861, "1400", ["Fortune", "Class"]),
  g("A Christmas Carol", "Charles Dickens", 1843, "46", ["Greed", "Redemption"]),
  g("Our Mutual Friend", "Charles Dickens", 1865, "883", ["Money", "Inheritance"]),
  g("Little Dorrit", "Charles Dickens", 1857, "963", ["Debt", "Society"]),
  g("Dombey and Son", "Charles Dickens", 1848, "821", ["Business", "Pride"]),
  g("Hard Times", "Charles Dickens", 1854, "786", ["Industry", "Society"]),
  g("Martin Chuzzlewit", "Charles Dickens", 1844, "968", ["Greed", "Selfishness"]),
  g("Nicholas Nickleby", "Charles Dickens", 1839, "967", ["Fortune"]),
  g("Oliver Twist", "Charles Dickens", 1838, "730", ["Poverty"]),
  g("Vanity Fair", "William Makepeace Thackeray", 1848, "599", ["Ambition", "Society"]),
  g("Silas Marner", "George Eliot", 1861, "550", ["Gold", "Redemption"]),
  g("Middlemarch", "George Eliot", 1871, "145", ["Ambition", "Society"]),
  g("The Way We Live Now", "Anthony Trollope", 1875, "5231", ["Finance", "Fraud"]),
  g("Doctor Thorne", "Anthony Trollope", 1858, "3166", ["Inheritance", "Class"]),
  g("Pride and Prejudice", "Jane Austen", 1813, "1342", ["Fortune", "Marriage"]),
  g("Sense and Sensibility", "Jane Austen", 1811, "161", ["Inheritance"]),
  g("Mansfield Park", "Jane Austen", 1814, "141", ["Class", "Fortune"]),
  g("Persuasion", "Jane Austen", 1817, "105", ["Fortune", "Class"]),
  g("Emma", "Jane Austen", 1815, "158", ["Society"]),
  g("Eugénie Grandet", "Honoré de Balzac", 1833, "1715", ["Miserliness", "Inheritance"]),
  g("Père Goriot", "Honoré de Balzac", 1835, "1237", ["Ambition", "Money"]),
  g("Germinal", "Émile Zola", 1885, "5711", ["Labor", "Industry"]),
  g("Money (L'Argent)", "Émile Zola", 1891, "", ["Finance", "Speculation"]),
  g("The Gambler", "Fyodor Dostoevsky", 1866, "2197", ["Gambling", "Money"]),
  g("Crime and Punishment", "Fyodor Dostoevsky", 1866, "2554", ["Poverty", "Morality"]),
  g("Poor Folk", "Fyodor Dostoevsky", 1846, "2302", ["Poverty"]),
  g("Dead Souls", "Nikolai Gogol", 1842, "1081", ["Schemes", "Society"]),
  g("Anna Karenina", "Leo Tolstoy", 1878, "1399", ["Society"]),
  g("The Financier", "Theodore Dreiser", 1912, "1840", ["Finance", "Ambition"]),
  g("The Titan", "Theodore Dreiser", 1914, "", ["Finance", "Power"]),
  g("Sister Carrie", "Theodore Dreiser", 1900, "233", ["Ambition", "City"]),
  g("The Rise of Silas Lapham", "William Dean Howells", 1885, "154", ["Business", "Ethics"]),
  g("The House of Mirth", "Edith Wharton", 1905, "284", ["Society", "Money"]),
  g("The Age of Innocence", "Edith Wharton", 1920, "541", ["Society"]),
  g("The Custom of the Country", "Edith Wharton", 1913, "", ["Ambition", "Society"]),
  g("The Great Gatsby", "F. Scott Fitzgerald", 1925, "64317", ["Wealth", "Ambition"]),
  g("Babbitt", "Sinclair Lewis", 1922, "1156", ["Business", "Conformity"]),
  g("The Jungle", "Upton Sinclair", 1906, "140", ["Labor", "Industry"]),
  g("The Octopus", "Frank Norris", 1901, "268", ["Business", "Power"]),
  g("The Pit", "Frank Norris", 1903, "", ["Speculation", "Markets"]),
  g("McTeague", "Frank Norris", 1899, "165", ["Greed", "Gold"]),
  g("The Gilded Age", "Mark Twain & Charles Dudley Warner", 1873, "3178", ["Speculation", "Satire"]),
  g("The Man That Corrupted Hadleyburg", "Mark Twain", 1899, "1213", ["Greed", "Honesty"]),
  g("The Prince and the Pauper", "Mark Twain", 1881, "1837", ["Class", "Fortune"]),
  g("Ragged Dick", "Horatio Alger", 1868, "5348", ["Rags to riches"]),
  g("North and South", "Elizabeth Gaskell", 1855, "4276", ["Industry", "Class"]),
  g("Mary Barton", "Elizabeth Gaskell", 1848, "2153", ["Labor", "Poverty"]),
  g("The Mayor of Casterbridge", "Thomas Hardy", 1886, "143", ["Business", "Fortune"]),
  g("Robinson Crusoe", "Daniel Defoe", 1719, "521", ["Enterprise", "Survival"]),
  g("Treasure Island", "Robert Louis Stevenson", 1883, "120", ["Treasure", "Adventure"]),
  g("The Merchant of Venice (Complete Works)", "William Shakespeare", 1600, "100", ["Debt", "Commerce"]),
  g("Candide", "Voltaire", 1759, "19942", ["Fortune", "Satire"]),
  g("Gulliver's Travels", "Jonathan Swift", 1726, "829", ["Satire", "Society"]),
  g("Erewhon", "Samuel Butler", 1872, "1906", ["Utopia", "Satire"]),
  g("The Way of All Flesh", "Samuel Butler", 1903, "2084", ["Inheritance", "Family"]),
  g("Idle Thoughts of an Idle Fellow", "Jerome K. Jerome", 1886, "849", ["Humor", "Money"]),
];