import React,{useState,useRef,useEffect} from 'react';
import { useInfiniteQuery,useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Heart,Plus,Loader2,ArrowUp,ArrowDown } from 'lucide-react';
import ClutchPublish from '@/components/clutchkas/ClutchPublish';
import ClutchTipSettings from '@/components/clutchkas/ClutchTipSettings';
import ClutchClipCard from '@/components/clutchkas/ClutchClipCard';
import { signInToClutch,validTip } from '@/components/clutchkas/clutchMedia';
export default function ClutchWorkspace({wallet}){
  const key='clutch-heart-'+wallet.address,client=useQueryClient(),feed=useRef(null);
  const [amount,setAmount]=useState(()=>localStorage.getItem(key)||''),[settings,setSettings]=useState(false),[publish,setPublish]=useState(false);
  const query=useInfiniteQuery({queryKey:['clutch-clips'],initialPageParam:null,queryFn:({pageParam})=>base44.entities.ClutchClip.filter(pageParam?{created_date:{$lt:pageParam}}:{},'-created_date',10),getNextPageParam:last=>last.length===10?last[last.length-1].created_date:undefined,retry:false});
  const clips=query.data?.pages.flat()||[],more=useRef(null);
  useEffect(()=>{if(!more.current||!query.hasNextPage||query.isFetchNextPageError)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!query.isFetchingNextPage)query.fetchNextPage();},{root:feed.current,rootMargin:'200px'});observer.observe(more.current);return()=>observer.disconnect();},[query.hasNextPage,query.isFetchingNextPage,query.isFetchNextPageError,query.fetchNextPage]);
  const saved=clip=>{client.setQueryData(['clutch-clips'],old=>old?{...old,pages:[[clip,...old.pages[0]],...old.pages.slice(1)]}:{pages:[[clip]],pageParams:[null]});setPublish(false);feed.current?.scrollTo({top:0});};
  const saveAmount=value=>{localStorage.setItem(key,value);setAmount(value);setSettings(false);};
  const scroll=direction=>{feed.current?.scrollBy({top:direction*feed.current.clientHeight,behavior:'smooth'});};
  return <main className="clutch-workspace"><div className="clutch-toolbar"><div><h1>The highlight reel</h1><p>Fan-funded. Player-owned.</p></div><div className="clutch-toolbar-actions"><button onClick={()=>scroll(-1)} aria-label="Previous clip"><ArrowUp size={16}/></button><button onClick={()=>scroll(1)} aria-label="Next clip"><ArrowDown size={16}/></button><button onClick={()=>setSettings(true)}><Heart size={16}/>{validTip(amount)?`${amount} KAS`:'Set heart'}</button><button onClick={()=>setPublish(true)}><Plus size={16}/>Post</button></div></div><div ref={feed} className="clutch-feed">{query.isPending?<div className="clutch-empty"><Loader2 className="animate-spin"/>Loading highlights…</div>:query.isError?<div className="clutch-empty"><h2>Couldn’t load the reel.</h2><p>{query.error?.message}</p><button onClick={()=>query.refetch()}>Retry</button><button onClick={signInToClutch}>Sign in to TTT</button></div>:!clips.length?<div className="clutch-empty"><Heart className="text-primary" size={32}/><h2>The first clutch is yours.</h2><p>No highlights yet. Upload your own VALORANT clip or share its YouTube link to start the reel.</p><button className="clutch-primary" onClick={()=>setPublish(true)}>Post the first highlight</button></div>:clips.map(clip=><ClutchClipCard key={clip.id} clip={clip} address={wallet.address} amount={amount} onConfigure={()=>setSettings(true)} onRefresh={wallet.refreshState} paused={settings||publish}/>)}{query.hasNextPage&&<div ref={more} className="clutch-load-more"><button disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage?'Loading…':'More highlights ↓'}</button></div>}{query.isFetchNextPageError&&<p className="clutch-error">Couldn’t load more highlights. Try again.</p>}</div>{settings&&<ClutchTipSettings amount={amount} onSave={saveAmount} onClose={()=>setSettings(false)}/>} {publish&&<ClutchPublish address={wallet.address} onClose={()=>setPublish(false)} onPublished={saved}/>}</main>;
}