import { base44 } from '@/api/base44Client';

const waitFor=(node,event)=>new Promise((resolve,reject)=>{node.addEventListener(event,resolve,{once:true});node.addEventListener('error',()=>reject(new Error('Could not read this video.')),{once:true});});
export async function getVideoDuration(file){const video=document.createElement('video');const url=URL.createObjectURL(file);video.preload='metadata';video.src=url;await waitFor(video,'loadedmetadata');const duration=video.duration;URL.revokeObjectURL(url);return duration;}
export async function planShort(fileUri,duration){
  const signed=await base44.integrations.Core.CreateFileSignedUrl({file_uri:fileUri,expires_in:1800});
  const plan=await base44.integrations.Core.InvokeLLM({file_urls:[signed.signed_url],prompt:`You are the CLUTCHKAS esports short editor. Watch this ${duration.toFixed(1)} second gameplay video. Build a punchy edited version from only the strongest action. Return 1-5 chronological segments totaling no more than 58 seconds. Remove dead time, menus, loading, and repetition. For each segment give exact start/end seconds, horizontal action focus from 0 (left) to 1 (right), and restrained crop zoom from 1 to 1.18. Never invent footage. Briefly summarize the edit.`,response_json_schema:{type:'object',properties:{summary:{type:'string'},segments:{type:'array',items:{type:'object',properties:{start:{type:'number'},end:{type:'number'},focus_x:{type:'number'},zoom:{type:'number'}},required:['start','end']}}},required:['segments']}});
  let used=0;const segments=(plan.segments||[]).sort((a,b)=>a.start-b.start).flatMap(s=>{const start=Math.max(0,Math.min(duration-.1,Number(s.start)||0));const available=Math.min(duration,Number(s.end)||duration)-start;const length=Math.min(Math.max(0,available),58-used);if(length<.5)return[];used+=length;return[{start,end:start+length,focus_x:Number.isFinite(Number(s.focus_x))?Math.max(0,Math.min(1,Number(s.focus_x))):.5,zoom:Math.max(1,Math.min(1.18,Number(s.zoom)||1.04))}];});
  return{summary:plan.summary||'AI removed downtime and focused the strongest play.',segments:segments.length?segments:[{start:0,end:Math.min(duration,58),focus_x:.5,zoom:1.03}]};
}
function draw(ctx,video,segment){const w=720,h=1280,sw=video.videoWidth,sh=video.videoHeight,zoom=segment.zoom||1;ctx.fillStyle='#050508';ctx.fillRect(0,0,w,h);const cropW=Math.min(sw,sh*w/h)/zoom,cropH=cropW*h/w;const maxX=sw-cropW,sx=Math.max(0,Math.min(maxX,maxX*(segment.focus_x??.5)));const sy=Math.max(0,(sh-cropH)/2);ctx.drawImage(video,sx,sy,cropW,cropH,0,0,w,h);ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,w,62);ctx.fillStyle='#fff';ctx.font='700 25px sans-serif';ctx.fillText('CLUTCHKAS',28,40);}
export async function renderShort(file,plan,onProgress){
  if(!window.MediaRecorder)throw new Error('This browser cannot create the AI edit. Try Chrome or Edge.');const video=document.createElement('video'),url=URL.createObjectURL(file);video.src=url;video.preload='auto';video.muted=true;video.playsInline=true;await waitFor(video,'loadedmetadata');const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1280;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),captured=video.captureStream?.();captured?.getAudioTracks().forEach(track=>stream.addTrack(track));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));const chunks=[],recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),total=plan.segments.reduce((n,s)=>n+s.end-s.start,0);let done=0;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const finished=new Promise(resolve=>recorder.onstop=resolve);recorder.start(1000);
  for(const segment of plan.segments){video.currentTime=segment.start;await waitFor(video,'seeked');await video.play();await new Promise(resolve=>{const frame=()=>{draw(ctx,video,segment);const elapsed=Math.max(0,Math.min(segment.end-segment.start,video.currentTime-segment.start));onProgress?.((done+elapsed)/total);if(video.currentTime>=segment.end||video.ended){video.pause();resolve();}else requestAnimationFrame(frame);};frame();});done+=segment.end-segment.start;}
  recorder.stop();await finished;URL.revokeObjectURL(url);stream.getTracks().forEach(track=>track.stop());return new File(chunks,`${file.name.replace(/\.[^.]+$/,'')}-clutchkas-ai.webm`,{type:mime?.split(';')[0]||'video/webm'});
}