import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';

const fresh = (kind,time=0) => kind === 'camera' ? {time,x:0,y:0,z:500,rotateX:0,rotateY:0,rotateZ:0,fov:50,easing:'easeOutInOut',curve:'0.42,0,0.58,1'} : kind === 'text' ? {time,x:0,y:0,scale:1,opacity:1,easing:'easeIn',curve:'0.42,0,1,1'} : {time,x:0,y:0,z:0,rotateX:0,rotateY:0,rotateZ:0,scale:1,easing:'linear',curve:'0,0,1,1'};
export default function ETA3DKeyframes({ title, kind='device', value, onChange }) {
  const items=value?.length?value:[fresh(kind,0),...(kind==='camera'?[]:[fresh(kind,7)])];
  const set=(i,key,next)=>onChange(items.map((item,n)=>n===i?{...item,[key]:next}:item));
  const fields=kind==='camera'?[['Position X','x'],['Position Y','y'],['Position Z','z'],['Rotation X','rotateX'],['Rotation Y','rotateY'],['Rotation Z','rotateZ'],['FOV','fov']]:kind==='text'?[['Position X','x'],['Position Y','y'],['Scale','scale'],['Opacity','opacity']]:[['Position X','x'],['Position Y','y'],['Position Z','z'],['Rotation X','rotateX'],['Rotation Y','rotateY'],['Rotation Z','rotateZ'],['Scale','scale']];
  return <div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold">{title}</h3><p className="text-[11px] text-muted-foreground">{items.map((item)=>`${Number(item.time).toFixed(1)}s`).join('  ')}</p></div><button onClick={()=>onChange([...items,fresh(kind,Number(items.at(-1)?.time||0)+1)])} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3"/> Add</button></div>{items.map((item,i)=><div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2"><ETAFormField label="At time (s)"><input className={etaInput} type="number" step=".1" value={item.time} onChange={(e)=>set(i,'time',Number(e.target.value))}/></ETAFormField>{fields.map(([label,key])=><ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={item[key]} onChange={(e)=>set(i,key,Number(e.target.value))}/></ETAFormField>)}<ETAFormField label="Easing (to next)"><select className={etaInput} value={item.easing} onChange={(e)=>set(i,'easing',e.target.value)}><option>linear</option><option>easeIn</option><option>easeOut</option><option>easeInOut</option><option>easeOutInOut</option><option>custom</option></select></ETAFormField><details className="rounded-lg border border-border p-2 text-xs"><summary className="cursor-pointer font-semibold">Edit Easing Curved Graph</summary><input className={`${etaInput} mt-2`} value={item.curve||''} placeholder="0.42,0,0.58,1" onChange={(e)=>set(i,'curve',e.target.value)}/></details><button onClick={()=>onChange(items.filter((_,n)=>n!==i))} className="flex items-center justify-center gap-1 rounded-lg border border-destructive/40 px-3 py-2 text-xs text-destructive"><Trash2 className="h-3 w-3"/> Delete this {kind==='text'?'text ':kind==='camera'?'camera ':''}keyframe</button></div>)}</div>;
}