import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';

const fields = [['Card width (px)','cardWidth',112],['Card height (px)','cardHeight',160],['Perspective','cardPerspective',900],['Halo X spread (px)','haloX',145],['Halo Y spread (px)','haloY',65],['Halo Z depth (px)','haloZ',120],['Strength (blur / Z)','depthStrength',35],['Max blur (px)','maxBlur',8],['Float value (deg)','floatRotation',5],['Float rotation speed','floatSpeed',20]];
const freshZoom = (time=0) => ({ time, focusCard:0, zoomOut:false, x:960, y:540, easing:'easeInOut' });
export default function ETACards4Controls({ advanced, setAdvanced }) {
  const zooms = advanced.cardZoomKeyframes || [freshZoom(1), freshZoom(2), freshZoom(8.7)];
  const setZoom = (i,key,value) => setAdvanced('cardZoomKeyframes', zooms.map((item,n) => n === i ? { ...item, [key]:value } : item));
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold">Zoom keyframes (3D camera)</h3><p className="text-[11px] text-muted-foreground">Focus individual cards or return to the wide halo.</p></div><button onClick={() => setAdvanced('cardZoomKeyframes', [...zooms, freshZoom(zooms.at(-1)?.time + 1)])} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3" /> Add</button></div>{zooms.map((zoom,i) => <div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2"><ETAFormField label="At time (s)"><input className={etaInput} type="number" step=".1" value={zoom.time} onChange={(e) => setZoom(i,'time',Number(e.target.value))} /></ETAFormField><ETAFormField label="Focus card"><input className={etaInput} type="number" min="0" value={zoom.focusCard} onChange={(e) => setZoom(i,'focusCard',Number(e.target.value))} /></ETAFormField><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={zoom.zoomOut} onChange={(e) => setZoom(i,'zoomOut',e.target.checked)} /> Zoom out (wide)</label><ETAFormField label="Zoom X (px)"><input className={etaInput} type="number" value={zoom.x} onChange={(e) => setZoom(i,'x',Number(e.target.value))} /></ETAFormField><ETAFormField label="Zoom Y (px)"><input className={etaInput} type="number" value={zoom.y} onChange={(e) => setZoom(i,'y',Number(e.target.value))} /></ETAFormField><ETAFormField label="Zoom easing"><select className={etaInput} value={zoom.easing} onChange={(e) => setZoom(i,'easing',e.target.value)}><option>easeInOut</option><option>easeIn</option><option>easeOut</option><option>linear</option><option>custom</option></select></ETAFormField><button onClick={() => setAdvanced('cardZoomKeyframes', zooms.filter((_,n) => n !== i))} className="flex items-center justify-center gap-1 rounded-lg border border-destructive/40 px-3 py-2 text-xs text-destructive"><Trash2 className="h-3 w-3" /> Remove keyframe</button></div>)}<div className="grid gap-3 sm:grid-cols-2">{fields.map(([label,key,fallback]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={advanced[key] ?? fallback} onChange={(e) => setAdvanced(key, Number(e.target.value))} /></ETAFormField>)}</div></div>;
}