import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';

const fresh = () => ({ time:0, panX:0, panY:0, depth:0, scale:1, rotateX:0, rotateY:0, rotateZ:0, originX:50, originY:50 });
const fields = [['At time (s)','time'],['Pan X (px)','panX'],['Pan Y (px)','panY'],['Depth (px)','depth'],['Camera zoom','scale'],['Tilt X (deg)','rotateX'],['Orbit Y (deg)','rotateY'],['Roll Z (deg)','rotateZ'],['Focus X (%)','originX'],['Focus Y (%)','originY']];
export default function ETACameraKeyframes({ value = [], onChange }) {
  const set = (index,key,next) => onChange(value.map((item,i) => i === index ? {...item,[key]:Number(next)} : item));
  return <section className="rounded-2xl border border-border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Camera movement keyframes</h2><p className="text-xs text-muted-foreground">Interpolated pan, zoom, depth, tilt, orbit and roll</p></div><button onClick={() => onChange([...value,fresh()])} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3" /> Add</button></div><div className="space-y-3">{value.length === 0 && <p className="text-xs text-muted-foreground">A cinematic camera path is applied automatically. Add keyframes to customize it.</p>}{value.map((item,index) => <div key={index} className="rounded-xl border border-border p-3"><div className="grid gap-3 sm:grid-cols-2">{fields.map(([label,key]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={item[key] ?? fresh()[key]} onChange={(e) => set(index,key,e.target.value)} /></ETAFormField>)}</div><button onClick={() => onChange(value.filter((_,i) => i !== index))} className="mt-3 flex items-center gap-1 text-xs text-destructive"><Trash2 className="h-3 w-3" /> Delete keyframe</button></div>)}</div></section>;
}