import React from 'react';
import { ImagePlus, Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';
import ETACardsMotionControls from './ETACardsMotionControls';
import ETACardsHeadlineControls from './ETACardsHeadlineControls';

const freshRing = () => ({ time:0, speed:20, radius:1, tiltX:8, tiltZ:0, textDepth:20, easing:'ease-in-out' });
export default function ETACardsSettings({ advanced, setAdvanced }) {
  const images = advanced.cardImages || [], rings = advanced.ringKeyframes || [];
  const addImages = (event) => setAdvanced('cardImages', [...images, ...Array.from(event.target.files || []).map((file) => ({ url:URL.createObjectURL(file), name:file.name }))]);
  const setRing = (i,key,val) => setAdvanced('ringKeyframes', rings.map((item,n) => n === i ? { ...item, [key]:val } : item));
  return <section className="space-y-5 rounded-2xl border border-border bg-card p-4"><div><h2 className="text-sm font-semibold">Cards</h2><p className="text-xs text-muted-foreground">Card Animation</p></div><div><p className="text-xs font-semibold">Card images</p><p className="mt-1 text-[11px] text-muted-foreground">Images picked here become the cards for this stack.</p>{images.length ? <div className="mt-2 flex gap-2 overflow-x-auto">{images.map((image,i) => <div key={i} className="relative shrink-0"><img src={image.url} alt={image.name} className="h-20 w-16 rounded-lg object-cover" /><button onClick={() => setAdvanced('cardImages', images.filter((_,n) => n !== i))} className="absolute right-1 top-1 rounded-full bg-background p-1"><Trash2 className="h-3 w-3" /></button></div>)}</div> : <p className="mt-2 text-xs text-muted-foreground">No custom images yet. The stack will use generated or default cards.</p>}<label className="mt-3 flex w-fit cursor-pointer items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><ImagePlus className="h-3 w-3" /> Add image<input type="file" accept="image/*" multiple className="hidden" onChange={addImages} /></label></div><ETACardsMotionControls advanced={advanced} setAdvanced={setAdvanced} /><ETACardsHeadlineControls advanced={advanced} setAdvanced={setAdvanced} /><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold">Sphere keyframes</h3><p className="text-[11px] text-muted-foreground">Animate spin, radius, tilt, and text depth.</p></div><button onClick={() => setAdvanced('ringKeyframes', [...rings, freshRing()])} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3" /> Add</button></div>{rings.map((ring,i) => <div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2">{[['At time (s)','time'],['Spin speed (°/s)','speed'],['Sphere radius scale','radius'],['Tilt X (deg)','tiltX'],['Tilt Z (deg)','tiltZ'],['Text depth Z (px)','textDepth']].map(([label,key]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={ring[key]} onChange={(e) => setRing(i,key,Number(e.target.value))} /></ETAFormField>)}<ETAFormField label="Keyframe easing"><select className={etaInput} value={ring.easing} onChange={(e) => setRing(i,'easing',e.target.value)}><option>linear</option><option>ease-in</option><option>ease-out</option><option>ease-in-out</option></select></ETAFormField></div>)}</section>;
}