import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';

const fields = [['Card width (px)','cardWidth',112],['Card height (px)','cardHeight',160],['Perspective','cardPerspective',900],['Halo X spread (px)','haloX',150],['Halo Y spread (px)','haloY',65],['Halo Z depth (px)','haloZ',120],['Strength (blur / Z)','depthStrength',35],['Max blur (px)','maxBlur',8],['Center text 3D drift strength','centerDriftStrength',1],['Min move (px)','centerDriftMin',2],['Max move (px)','centerDriftMax',12],['Base X (px)','haloBaseX',0],['Base Y (px)','haloBaseY',0],['Base Z (px)','haloBaseZ',0]];
const freshMove = (time=0) => ({ time, x:0, y:0, z:0, easing:'easeInOut' });
export default function ETACards3Controls({ advanced, setAdvanced }) {
  const moves = advanced.haloMoveKeyframes || [freshMove(0), freshMove(7)];
  const setMove = (i,key,value) => setAdvanced('haloMoveKeyframes', moves.map((item,n) => n === i ? { ...item, [key]:value } : item));
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2">{fields.map(([label,key,fallback]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={advanced[key] ?? fallback} onChange={(e) => setAdvanced(key, Number(e.target.value))} /></ETAFormField>)}</div><div className="grid gap-3 sm:grid-cols-2"><ETAFormField label="Center text"><input className={etaInput} value={advanced.centerHeadline || ''} placeholder="e.g. with" onChange={(e) => setAdvanced('centerHeadline', e.target.value)} /></ETAFormField><ETAFormField label="Center text color"><input className={etaInput} type="color" value={advanced.centerTextColor || '#ffffff'} onChange={(e) => setAdvanced('centerTextColor', e.target.value)} /></ETAFormField><ETAFormField label="Center text font family"><select className={etaInput} value={advanced.cardFont || 'SF Pro Display'} onChange={(e) => setAdvanced('cardFont', e.target.value)}><option>SF Pro Display</option><option>Space Grotesk</option><option>Fraunces</option><option>Inter</option></select></ETAFormField><ETAFormField label="Center text font size (px)"><input className={etaInput} type="number" value={advanced.cardFontSize ?? 28} onChange={(e) => setAdvanced('cardFontSize', Number(e.target.value))} /></ETAFormField><ETAFormField label="Center text font weight"><input className={etaInput} type="number" step="100" min="100" max="900" value={advanced.cardFontWeight ?? 700} onChange={(e) => setAdvanced('cardFontWeight', Number(e.target.value))} /></ETAFormField></div><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold">Halo group move (3D)</h3><p className="text-[11px] text-muted-foreground">Timed movement for the complete card halo.</p></div><button onClick={() => setAdvanced('haloMoveKeyframes', [...moves, freshMove(moves.at(-1)?.time + 1)])} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3" /> Add</button></div>{moves.map((move,i) => <div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2">{[['At time (s)','time'],['Move X (px)','x'],['Move Y (px)','y'],['Move Z (px)','z']].map(([label,key]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".1" value={move[key]} onChange={(e) => setMove(i,key,Number(e.target.value))} /></ETAFormField>)}<ETAFormField label="Keyframe easing"><select className={etaInput} value={move.easing} onChange={(e) => setMove(i,'easing',e.target.value)}><option>easeInOut</option><option>easeIn</option><option>easeOut</option><option>linear</option><option>custom</option></select></ETAFormField><button onClick={() => setAdvanced('haloMoveKeyframes', moves.filter((_,n) => n !== i))} className="flex items-center justify-center gap-1 rounded-lg border border-destructive/40 px-3 py-2 text-xs text-destructive"><Trash2 className="h-3 w-3" /> Remove</button></div>)}</div>;
}