import React from 'react';
import ETAFormField, { etaInput } from './ETAFormField';

const defaults = { enabled: true, direction: 'Left', outgoing: { duration: .25, distance: .5, drift: .15, driftDuration: 2.5, curve: 'ease-out', easing: 'ease-in-out' }, incoming: { ratio: 'Golden ratio (1:2)', duration: .5, distance: .5, opacity: 0, scale: 1, easing: 'ease-in-out', direction: 'zoomIn' } };
export default function ETAMatchCutPanel({ value, onChange, previous }) {
  const data = { ...defaults, ...value, outgoing: { ...defaults.outgoing, ...value?.outgoing }, incoming: { ...defaults.incoming, ...value?.incoming } };
  const set = (key, next) => onChange({ ...data, [key]: next });
  const nested = (group, key, next) => onChange({ ...data, [group]: { ...data[group], [key]: next } });
  const prev = previous?.advanced?.matchCut?.incoming;
  return <section className="space-y-5 rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Match cut</h2><p className="text-xs text-muted-foreground">Match cut to next scene</p></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={!data.enabled} onChange={(e) => set('enabled', !e.target.checked)} /> Disable match cut</label></div><ETAFormField label="Direction"><select className={etaInput} value={data.direction} onChange={(e) => set('direction', e.target.value)}><option>Left</option><option>Right</option><option>Up</option><option>Down</option><option>Zoom</option></select></ETAFormField><CutGroup title="Outgoing (this scene exits)" values={data.outgoing} fields={[['Duration (s)','duration'],['Slide distance (0–1)','distance'],['Drift amount (0–1)','drift'],['Drift over last (s)','driftDuration']]} onSet={(key,val) => nested('outgoing',key,val)} easingKey="curve" easingLabel="Drift curve (outgoing)" secondaryEasing /><CutGroup title="Incoming (next scene enters)" values={data.incoming} fields={[['Duration (s)','duration'],['Slide distance (0–1)','distance'],['Opacity (start)','opacity'],['Scale (start)','scale']]} onSet={(key,val) => nested('incoming',key,val)} easingKey="easing" easingLabel="Easing graph (incoming)" ratio /><div className="rounded-xl border border-border bg-muted/40 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">From previous scene (read-only)</p><p className="mt-2 text-xs">Your entrance: {Math.round(Number(prev?.duration || 1) * 30)} frames, direction: {prev?.direction || 'zoomIn'}.</p></div></section>;
}
function CutGroup({ title, values, fields, onSet, easingKey, easingLabel, ratio, secondaryEasing }) { return <div><h3 className="mb-3 text-xs font-semibold">{title}</h3><div className="grid gap-3 sm:grid-cols-2">{ratio && <ETAFormField label="Entrance ratio"><select className={etaInput} value={values.ratio || 'Golden ratio (1:2)'} onChange={(e) => onSet('ratio', e.target.value)}><option>Golden ratio (1:2)</option><option>Balanced (1:1)</option><option>Quick entrance (2:1)</option></select></ETAFormField>}{fields.map(([label,key]) => <ETAFormField key={key} label={label}><input className={etaInput} type="number" step=".01" value={values[key]} onChange={(e) => onSet(key, Number(e.target.value))} /></ETAFormField>)}<ETAFormField label={easingLabel}><select className={etaInput} value={values[easingKey]} onChange={(e) => onSet(easingKey, e.target.value)}><option>linear</option><option>ease-in</option><option>ease-out</option><option>ease-in-out</option><option>custom</option></select></ETAFormField>{secondaryEasing && <ETAFormField label="Easing graph (outgoing)"><select className={etaInput} value={values.easing || 'ease-in-out'} onChange={(e) => onSet('easing', e.target.value)}><option>linear</option><option>ease-in</option><option>ease-out</option><option>ease-in-out</option><option>custom</option></select></ETAFormField>}</div></div>; }