import React from 'react';
import { ArrowRight, List, Play, Sparkles, Wand2 } from 'lucide-react';

const clamp = (lines) => ({display:'-webkit-box',WebkitLineClamp:lines,WebkitBoxOrient:'vertical',overflow:'hidden'});
const reveal = (frameProgress,duration,start=0) => { const t=Math.max(0,Math.min(1,((frameProgress??1)*duration-start)/.35)); return {opacity:t,transform:`translateY(${(1-t)*18}px)`}; };
function Hero({ style }) { return <div style={style} className="relative min-h-0 overflow-hidden rounded-[1.15rem] border border-white/20 bg-[radial-gradient(circle_at_15%_20%,#b8ff3d_0%,#526d22_28%,#15171b_68%)] shadow-[0_0_32px_rgba(184,255,61,.22)]"><div className="absolute inset-x-[10%] bottom-[12%] top-[18%] overflow-hidden rounded-[1rem] border border-white/25 bg-gradient-to-br from-[#25282d] to-[#090a0c] shadow-2xl"><i className="absolute left-[12%] top-[46%] h-[10%] w-[48%] rounded-full bg-[#b8ff3d]"/><i className="absolute -right-[8%] top-[18%] h-[55%] w-[64%] -rotate-[16deg] rounded-[50%] border-t-[12px] border-[#d9ff98] opacity-90"/><i className="absolute bottom-0 right-[28%] h-[68%] w-px bg-white/50"/></div></div>; }
function Feature({ item, icon, style, compact=false }) { return <article style={style} className={`flex min-h-0 overflow-hidden rounded-[1rem] border border-white/15 bg-[#202226]/95 ${compact?'items-center gap-[4%] px-[5%]':'items-center gap-[5%] px-[6%]'}`}><span className="grid aspect-square w-[22%] shrink-0 grid-cols-2 place-items-center gap-1 rounded-xl bg-white/5 text-[#b8ff3d]">{icon}</span><div className="min-w-0 overflow-hidden"><h3 style={clamp(2)} className="text-[clamp(9px,1.15vw,16px)] font-semibold leading-[1.08]">{item.title}</h3><p style={clamp(compact?2:3)} className="mt-1 text-[clamp(7px,.78vw,11px)] leading-[1.18] text-white/55">{item.body}</p></div></article>; }
export default function ETAPhoneStoryLayouts({ scene, advanced, frameProgress }) {
  const duration=Math.max(1,Number(scene.duration||3)), timing=advanced.phoneHyperframes||{}, cards=(advanced.phoneFeatureCards?.length?advanced.phoneFeatureCards:[{title:scene.purpose,body:scene.visual||scene.voiceover},{title:scene.motion,body:scene.transition}]).slice(0,2), variant=advanced.phoneUiVariant||['product-story','feature-stack','launch-feed'][String(scene.headline).length%3];
  const title=<h2 style={{...clamp(3),...reveal(frameProgress,duration,timing.titleStart??.08)}} className={`${variant==='product-story'?'mx-auto max-w-[92%] text-center':'text-left'} text-[clamp(17px,2.45vw,33px)] font-medium leading-[1.02] tracking-[-0.04em]`}>{scene.headline}</h2>;
  const hero=<Hero style={reveal(frameProgress,duration,timing.heroStart??.3)}/>;
  const first=<Feature item={cards[0]} icon={<><Sparkles/><Wand2/></>} style={reveal(frameProgress,duration,timing.card1Start??.65)}/>;
  const second=<Feature item={cards[1]||cards[0]} icon={<><Play/><List/></>} style={reveal(frameProgress,duration,timing.card2Start??.95)} compact={variant==='launch-feed'}/>;
  return <div className="flex min-h-0 flex-1 flex-col overflow-hidden">{variant!=='product-story'&&<p style={reveal(frameProgress,duration,.02)} className="mb-[3%] text-[clamp(7px,.7vw,10px)] font-semibold uppercase tracking-[.18em] text-[#b8ff3d]">{advanced.phoneEyebrow||scene.purpose}</p>}{title}<div className={`mt-[6%] grid min-h-0 flex-1 gap-[3%] ${variant==='feature-stack'?'grid-rows-[.8fr_1.25fr_.75fr]':'grid-rows-[1.15fr_1fr_1fr]'}`}>{hero}{first}{second}</div><div style={reveal(frameProgress,duration,timing.ctaStart??1.25)} className="mt-[4%] flex h-[7%] shrink-0 items-center justify-center gap-2 rounded-full bg-[#b8ff3d] text-[clamp(9px,1vw,14px)] font-bold text-black">{advanced.ctaLabel||'Continue'}<ArrowRight className="w-[1em]"/></div></div>;
}