import React from 'react';
import { motion } from 'framer-motion';
import { Search } from 'lucide-react';

const words = (text = '') => text.split(/\s+/).filter(Boolean);
export function TitleScene({ scene }) { return <div className="flex max-w-xl flex-wrap justify-center gap-x-3 gap-y-1 text-center font-heading text-4xl font-semibold sm:text-5xl">{words(scene.headline).map((word,i)=><motion.span key={`${word}-${i}`} initial={{y:30,opacity:0,filter:'blur(8px)'}} animate={{y:0,opacity:1,filter:'blur(0px)'}} transition={{delay:i*.1,duration:.55}}>{word}</motion.span>)}</div>; }
export function NumberScene({ scene }) { const match=scene.headline.match(/[\d,.]+/); return <div className="text-center"><motion.div initial={{scale:.35,opacity:0}} animate={{scale:[.35,1.08,1],opacity:1}} transition={{duration:1,ease:'easeOut'}} className="font-heading text-7xl font-semibold tabular-nums text-primary sm:text-8xl">{match?.[0]||scene.headline}</motion.div><motion.div initial={{width:0}} animate={{width:'100%'}} transition={{delay:.45,duration:1}} className="mx-auto mt-3 h-1 max-w-44 bg-primary" /></div>; }
export function SearchScene({ scene, advanced }) { const text=advanced.searchText||scene.headline; return <motion.div initial={{width:56}} animate={{width:'min(100%, 430px)'}} transition={{duration:.8,ease:'easeInOut'}} className="overflow-hidden rounded-full border border-primary/60 bg-background/80 p-1 shadow-[0_0_35px_hsl(var(--primary)/.16)]"><div className="flex h-12 items-center gap-3 px-4"><motion.div animate={{rotate:[0,-12,12,0]}} transition={{delay:.8,duration:.4}}><Search className="h-5 w-5 text-primary" /></motion.div><div className="flex min-w-0">{text.split('').map((char,i)=><motion.span key={i} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.7+i*.035}} className="whitespace-pre text-sm">{char}</motion.span>)}</div><motion.i animate={{opacity:[1,0,1]}} transition={{repeat:Infinity,duration:.8}} className="h-5 w-px bg-primary" /></div></motion.div>; }
export function LogoScene() { return <motion.div animate={{rotate:360}} transition={{duration:8,repeat:Infinity,ease:'linear'}} className="relative grid h-32 w-32 place-items-center rounded-full border border-primary/30"><motion.div initial={{scale:0}} animate={{scale:[0,1.2,1]}} transition={{duration:.9}} className="h-14 w-14 rotate-45 rounded-2xl bg-primary"/><motion.i animate={{rotate:-720}} transition={{duration:6,repeat:Infinity,ease:'linear'}} className="absolute h-24 w-8 rounded-full border-2 border-foreground/70"/></motion.div>; }
export function MorphScene() { return <motion.div animate={{borderRadius:['16%','50%','12%','42%','16%'],rotate:[0,90,180,270,360],scale:[.8,1.1,.9,1,.8]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut'}} className="h-36 w-36 bg-primary shadow-[0_0_60px_hsl(var(--primary)/.25)]"/>; }
export function UIScene({ scene }) { return <div className="grid w-full max-w-md grid-cols-3 gap-3"><motion.div initial={{x:-40,opacity:0}} animate={{x:0,opacity:1}} className="col-span-1 h-40 rounded-xl border border-border bg-background p-3">{[1,2,3,4].map((n)=><motion.i key={n} initial={{width:0}} animate={{width:`${45+n*10}%`}} transition={{delay:n*.15}} className="mb-3 block h-2 rounded bg-muted"/>)}</motion.div><motion.div initial={{y:35,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.2}} className="col-span-2 h-40 rounded-xl border border-border bg-background p-4"><p className="text-sm font-semibold">{scene.headline}</p><div className="mt-5 flex h-20 items-end gap-2">{[38,70,52,88,64].map((h,i)=><motion.i key={i} initial={{height:0}} animate={{height:`${h}%`}} transition={{delay:.35+i*.12}} className="flex-1 rounded-t bg-primary/80"/>)}</div></motion.div></div>; }