import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import ETAFormField, { etaInput } from './ETAFormField';

export default function ETAZoomCursorPanel({ advanced, setAdvanced }) {
  const zooms = advanced.zoomKeyframes || [], cursors = advanced.cursorSteps || [];
  const update = (name, list, i, key, val) => setAdvanced(name, list.map((item, n) => n === i ? { ...item, [key]: val } : item));
  return <section className="space-y-5 rounded-2xl border border-border bg-card p-4"><ListTitle title="Zoom keyframes" onAdd={() => setAdvanced('zoomKeyframes', [...zooms, { time: 1, selector: '', x: 0, y: 0, scale: 1.5, duration: 'default', easing: 'ease-in-out' }])} />{zooms.map((z,i) => <div key={i} className="rounded-xl border border-border p-3"><div className="grid gap-3 sm:grid-cols-2">{[['At time (s)','time','number'],['Selector (empty = zoom out or use X,Y)','selector','text'],['Zoom X (px)','x','number'],['Zoom Y (px)','y','number'],['Scale zoom','scale','number'],['Zoom duration (frames)','duration','text']].map(([label,key,type]) => <ETAFormField key={key} label={label}><input className={etaInput} type={type} step=".1" value={z[key]} onChange={(e) => update('zoomKeyframes',zooms,i,key,type === 'number' ? Number(e.target.value) : e.target.value)} /></ETAFormField>)}<ETAFormField label="Zoom easing"><select className={etaInput} value={z.easing} onChange={(e) => update('zoomKeyframes',zooms,i,'easing',e.target.value)}><option>linear</option><option>ease-in</option><option>ease-out</option><option>ease-in-out</option><option>custom</option></select></ETAFormField></div><Delete onClick={() => setAdvanced('zoomKeyframes', zooms.filter((_,n) => n !== i))} /></div>)}<ListTitle title="Cursor steps" onAdd={() => setAdvanced('cursorSteps', [...cursors, { time: 4, selector: '.send-button', duration: 1, action: 'Click' }])} />{cursors.map((c,i) => <div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2">{[['Start time (s)','time','number'],['Target selector','selector','text'],['Duration (s)','duration','number'],['Action','action','text']].map(([label,key,type]) => <ETAFormField key={key} label={label}><input className={etaInput} type={type} value={c[key]} onChange={(e) => update('cursorSteps',cursors,i,key,type === 'number' ? Number(e.target.value) : e.target.value)} /></ETAFormField>)}<Delete onClick={() => setAdvanced('cursorSteps', cursors.filter((_,n) => n !== i))} /></div>)}</section>;
}
function ListTitle({ title, onAdd }) { return <div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{title}</h2><button onClick={onAdd} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs"><Plus className="h-3 w-3" /> Add</button></div>; }
function Delete({ onClick }) { return <button onClick={onClick} className="ml-auto text-destructive"><Trash2 className="h-4 w-4" /></button>; }