import React, { useState } from 'react';
import { Send, Loader2, Sparkles } from 'lucide-react';
import { base44 } from '@/api/base44Client';
const schema = { type: 'object', properties: { message: { type: 'string' }, actions: { type: 'array', items: { type: 'object', properties: { type: { type: 'string', enum: ['set_mode','set_ratio','set_motion','set_easing','set_duration','set_background','set_rotation','set_zoom','set_radius','set_shadow','auto_frame','toggle_corners','record_movement','stop_recording','transform_selected','select_asset','duplicate_selected','remove_selected','play','pause','compose','undo','open_library','add_media','export'] }, value: { type: 'string' }, number_value: { type: 'number' }, x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' }, scale: { type: 'number' }, rotation: { type: 'number' } }, required: ['type'] } } }, required: ['message','actions'] };
export default function CameraDirectorChat({ project, execute }) {
  const [text, setText] = useState(''), [busy, setBusy] = useState(false), [messages, setMessages] = useState([{ role: 'director', text: 'Tell me how to edit the scene, move layers, change camera settings, compose, play, or export.' }]);
  const send = async event => { event.preventDefault(); const request = text.trim(); if (!request || busy) return; setText(''); setBusy(true); setMessages(items => [...items, { role: 'user', text: request }]);
    try { const result = await base44.integrations.Core.InvokeLLM({ prompt: `You control Camera Studio. Convert the request into only the allowed actions. Current mode: ${project.settings.mode}; ratio: ${project.settings.ratio}; selected layer: ${project.assets.find(a => a.id === project.selected)?.name || 'none'}; layers: ${project.assets.map(a => a.name).join(', ') || 'none'}. Values: mode photo/video; ratio 16:9/9:16/1:1/4:3; motion push/orbit/float; easing auto/linear/easeIn/easeOut/easeInOut. Use record_movement before animated dragging and stop_recording to finish. Zoom uses number_value 0.4–1.8, radius 0–0.25, shadow 0–0.7. x/y layer positions are -0.9 to 0.9, scale 0.15 to 4. Request: ${request}`, response_json_schema: schema }); execute(result.actions || []); setMessages(items => [...items, { role: 'director', text: result.message }]); }
    catch (error) { setMessages(items => [...items, { role: 'director', text: error.message || 'I could not apply that edit.' }]); } finally { setBusy(false); }
  };
  return <section className="camera-director"><div className="camera-director-log">{messages.slice(-3).map((message, index) => <p key={index} data-role={message.role}>{message.role === 'director' && <Sparkles size={11}/>}<span>{message.text}</span></p>)}</div><form onSubmit={send}><input value={text} onChange={event => setText(event.target.value)} placeholder="Ask Director to control this scene…" aria-label="Camera Director command" disabled={busy}/><button disabled={busy || !text.trim()}>{busy ? <Loader2 size={14} className="animate-spin"/> : <Send size={14}/>}<span>Send</span></button></form></section>;
}