// Maps DD Store app names to their website domain for favicon-based logos.
// Used by DDAppLogo to render real brand logos via Google's favicon service.
export const DD_APP_DOMAINS = {
  // AI
  ChatGPT: "chatgpt.com",
  "Google Gemini": "gemini.google.com",
  Claude: "claude.ai",
  "Grok AI": "x.ai",
  "Meta AI": "meta.ai",
  "Microsoft Copilot": "copilot.microsoft.com",
  Perplexity: "perplexity.ai",
  Cici: "cici.com",
  Pi: "pi.ai",
  Replika: "replika.com",
  // Productivity
  Gmail: "gmail.com",
  "Microsoft Outlook": "outlook.live.com",
  "Google Drive": "drive.google.com",
  "Google Docs": "docs.google.com",
  "Google Sheets": "sheets.google.com",
  "Google Slides": "slides.google.com",
  "Google Calendar": "calendar.google.com",
  "Microsoft Word": "microsoft.com",
  "Microsoft Excel": "microsoft.com",
  "Microsoft OneDrive": "onedrive.live.com",
  Notion: "notion.so",
  Todoist: "todoist.com",
  "Things 3": "culturedcode.com",
  Evernote: "evernote.com",
  Bear: "bear.app",
  Obsidian: "obsidian.md",
  "1Password": "1password.com",
  Bitwarden: "bitwarden.com",
  "Microsoft To Do": "todo.microsoft.com",
  "Apple Reminders": "apple.com",
  // Utilities
  CamScanner: "camscanner.com",
  "Adobe Scan": "adobe.com",
  "Adobe Acrobat": "adobe.com",
  "Adobe Fill & Sign": "adobe.com",
  "Scanner Pro": "readdle.com",
  "VFlat Scan": "vflat.com",
  "Genius Scan": "thegrizzlylabs.com",
  "Google Maps": "maps.google.com",
  Waze: "waze.com",
  Citymapper: "citymapper.com",
  Transit: "transitapp.com",
  Moovit: "moovit.com",
  "Google Translate": "translate.google.com",
  Life360: "life360.com",
  Yelp: "yelp.com",
  OpenTable: "opentable.com",
  Vinted: "vinted.com",
  Depop: "depop.com",
  Temu: "temu.com",
  "7 Brew Coffee": "7brew.com",
  HP: "hp.com",
  "Smart Home Manager": "att.com",
  // Travel
  Uber: "uber.com",
  Lyft: "lyft.com",
  Airbnb: "airbnb.com",
  "Booking.com": "booking.com",
  Expedia: "expedia.com",
  Hopper: "hopper.com",
  TripIt: "tripit.com",
  Duolingo: "duolingo.com",
  // Finance
  DoorDash: "doordash.com",
  "Uber Eats": "ubereats.com",
  Instacart: "instacart.com",
  "Cash App": "cash.app",
  Venmo: "venmo.com",
  PayPal: "paypal.com",
  Mint: "mint.intuit.com",
  YNAB: "ynab.com",
  "Credit Karma": "creditkarma.com",
  Robinhood: "robinhood.com",
  Coinbase: "coinbase.com",
  // Communication
  WhatsApp: "whatsapp.com",
  Threads: "threads.net",
  Telegram: "telegram.org",
  Signal: "signal.org",
  Discord: "discord.com",
  Slack: "slack.com",
  Zoom: "zoom.us",
  "Google Meet": "meet.google.com",
  "Microsoft Teams": "teams.microsoft.com",
  FaceTime: "apple.com",
  // Creative
  CapCut: "capcut.com",
  Spotify: "spotify.com",
  "Apple Music": "apple.com",
  "YouTube Music": "music.youtube.com",
  Shazam: "shazam.com",
  SoundCloud: "soundcloud.com",
  Audible: "audible.com",
  Libby: "overdrive.com",
  Kindle: "amazon.com",
  Goodreads: "goodreads.com",
  Pinterest: "pinterest.com",
  // Social
  Instagram: "instagram.com",
  YouTube: "youtube.com",
  TikTok: "tiktok.com",
  Snapchat: "snapchat.com",
  Reddit: "reddit.com",
  LinkedIn: "linkedin.com",
  Facebook: "facebook.com",
  X: "x.com",
  Kick: "kick.com",
  Twitch: "twitch.tv",
};

// Brand colors for letter-avatar fallback (first letter of app name)
export const DD_APP_COLORS = {
  ChatGPT: "#10a37f",
  "Google Gemini": "#4285f4",
  Claude: "#d97757",
  "Grok AI": "#000000",
  "Meta AI": "#0866ff",
  "Microsoft Copilot": "#0078d4",
  Perplexity: "#20808d",
  Cici: "#ff6b35",
  Pi: "#7c3aed",
  Replika: "#ff5a5f",
};