// DD Store — 100 applications across 8 categories.
export const DD_STORE_CATEGORIES = ["AI", "Productivity", "Communication", "Creative", "Travel", "Finance", "Social", "Utilities"];

const E = {
  AI: "✨", Productivity: "⚡", Communication: "💬", Creative: "🎨",
  Travel: "✈️", Finance: "💳", Social: "👤", Utilities: "🧰",
};

export const DD_STORE_APPS = [
  ["ChatGPT","AI","Everyday AI assistant"],["Google Gemini","AI","AI assistant from Google"],["Claude","AI","AI for life & work"],["Grok AI","AI","AI chat & video gen"],["Meta AI","AI","Personal AI assistant"],["Microsoft Copilot","AI","AI productivity"],["Perplexity","AI","Answer engine w/ sources"],["Cici","AI","AI companion chat"],["Pi","AI","Empathetic AI coach"],["Replika","AI","AI friend & companion"],
  ["Gmail","Productivity","Secure organized email"],["Microsoft Outlook","Productivity","Email, calendar & files"],["Google Drive","Productivity","Cloud file storage & scan"],["Google Docs","Productivity","Document collaboration"],["Google Sheets","Productivity","Collaborative spreadsheets"],["Google Slides","Productivity","Presentations"],["Google Calendar","Productivity","Plan & schedule"],["Microsoft Word","Productivity","Docs, resume, PDF"],["Microsoft Excel","Productivity","Data & budgets"],["Microsoft OneDrive","Productivity","Cloud storage"],["Notion","Productivity","Notes, wiki & databases"],["Todoist","Productivity","Task manager"],["Things 3","Productivity","Task manager"],["Evernote","Productivity","Notes & capture"],["Bear","Productivity","Markdown notes"],["Obsidian","Productivity","Linked knowledge notes"],["1Password","Productivity","Password manager"],["Bitwarden","Productivity","Open-source passwords"],["Microsoft To Do","Productivity","Task lists"],["Apple Reminders","Productivity","Reminders & lists"],
  ["CamScanner","Utilities","PDF scanner & converter"],["Adobe Scan","Utilities","Document scanner"],["Adobe Acrobat","Utilities","PDF reader"],["Adobe Fill & Sign","Utilities","PDF forms"],["Scanner Pro","Utilities","Document scanner"],["VFlat Scan","Utilities","Book scanner"],["Genius Scan","Utilities","PDF scanner"],["Google Maps","Utilities","Navigation & traffic"],["Waze","Utilities","Community traffic nav"],["Citymapper","Utilities","Transit routing"],["Transit","Utilities","Real-time transit"],["Moovit","Utilities","Transit directions"],["Google Translate","Utilities","Language translation"],["Life360","Utilities","Family GPS safety"],["Yelp","Utilities","Local reviews"],
  ["OpenTable","Utilities","Restaurant reservations"],["Uber","Travel","Rideshare"],["Lyft","Travel","Rideshare"],["Airbnb","Travel","Stays & experiences"],["Booking.com","Travel","Hotel booking"],["Expedia","Travel","Travel booking"],["Hopper","Travel","Price prediction"],["TripIt","Travel","Travel itinerary"],["Duolingo","Travel","Language learning"],
  ["DoorDash","Finance","Food & grocery delivery"],["Uber Eats","Finance","Food delivery"],["Instacart","Finance","Grocery delivery"],["Cash App","Finance","Payments"],["Venmo","Finance","Peer payments"],["PayPal","Finance","Payments"],["Mint","Finance","Budget tracking"],["YNAB","Finance","Budgeting"],["Credit Karma","Finance","Credit scores"],["Robinhood","Finance","Investing"],["Coinbase","Finance","Crypto exchange"],
  ["WhatsApp","Communication","Messaging"],["Threads","Communication","Text conversations"],["Telegram","Communication","Messenger"],["Signal","Communication","Private messenger"],["Discord","Communication","Community chat"],["Slack","Communication","Team messaging"],["Zoom","Communication","Video meetings"],["Google Meet","Communication","Video calls"],["Microsoft Teams","Communication","Work chat & meet"],["FaceTime","Communication","Video calls"],
  ["CapCut","Creative","Photo & video editor"],["Spotify","Creative","Music streaming"],["Apple Music","Creative","Music streaming"],["YouTube Music","Creative","Music streaming"],["Shazam","Creative","Song identification"],["SoundCloud","Creative","Audio platform"],["Audible","Creative","Audiobooks"],["Libby","Creative","Library ebooks"],["Kindle","Creative","Ebooks"],["Goodreads","Creative","Book reviews"],["Pinterest","Creative","Visual discovery"],
  ["Instagram","Social","Photo & video social"],["YouTube","Social","Video platform"],["TikTok","Social","Short video"],["Snapchat","Social","Visual messaging"],["Reddit","Social","Community forums"],["LinkedIn","Social","Professional network"],["Facebook","Social","Social network"],["X","Social","Social & news"],["Kick","Social","Live streaming"],["Twitch","Social","Live streaming"],
  ["Vinted","Utilities","Secondhand marketplace"],["Depop","Utilities","Thrift marketplace"],["Temu","Utilities","Deals marketplace"],["7 Brew Coffee","Utilities","Coffee ordering"],["HP","Utilities","Printer & devices"],["Smart Home Manager","Utilities","Home network"],
].map(([name, category, desc]) => ({ name, category, desc, icon: E[category] }));