/**
 * MIRAGE Tools — each tool wraps a TTT app's capability and is named after that app.
 * MIRAGE is the orchestrator that wires them together.
 */

export const MIRAGE_LOGO = "https://media.base44.com/images/public/6901295fa9bcfaa0f5ba2c2a/3d8269a23_generated_image.png";

export const MIRAGE_TOOLS = [
  // ─── IMAGE / VISUAL ───
  {
    id: "hikaru",
    appName: "Hikaru",
    label: "Hikaru",
    sublabel: "AI Image Studio",
    capability: "image",
    icon: "ImageIcon",
    color: "from-pink-500 to-rose-500",
    desc: "Generate cinematic images from a prompt",
    category: "Visual",
    path: "/Hikaru",
    inputs: ["text"],
    outputs: ["image"],
    defaultConfig: { prompt: "A glowing crystal city at sunset, cinematic, ultra detail" },
  },
  {
    id: "lumalabs",
    appName: "LumaLabs",
    label: "LumaLabs",
    sublabel: "Photoreal Frames",
    capability: "image",
    icon: "Camera",
    color: "from-purple-500 to-fuchsia-500",
    desc: "Photo-realistic visual frames (style-locked)",
    category: "Visual",
    path: "/Hikaru",
    inputs: ["text"],
    outputs: ["image"],
    defaultConfig: { prompt: "Photorealistic 35mm shot of a misty forest at dawn" },
  },
  {
    id: "speed",
    appName: "Speed",
    label: "Speed",
    sublabel: "Fast Image Gen",
    capability: "image",
    icon: "Zap",
    color: "from-amber-500 to-orange-500",
    desc: "Quick low-latency image generation",
    category: "Visual",
    path: "/Speed",
    inputs: ["text"],
    outputs: ["image"],
    defaultConfig: { prompt: "Minimalist abstract gradient, vibrant" },
  },
  {
    id: "kpaint",
    appName: "KPaint",
    label: "KPaint",
    sublabel: "Stylized Art",
    capability: "image",
    icon: "Palette",
    color: "from-violet-500 to-indigo-500",
    desc: "Stylized illustration art",
    category: "Visual",
    path: "/KPaint",
    inputs: ["text"],
    outputs: ["image"],
    defaultConfig: { prompt: "Watercolor illustration of a fox in the forest" },
  },

  // ─── TEXT / AI ───
  {
    id: "zeku",
    appName: "Zeku AI",
    label: "Zeku AI",
    sublabel: "LLM Reasoning",
    capability: "llm",
    icon: "Brain",
    color: "from-cyan-500 to-blue-500",
    desc: "Run a prompt through the LLM",
    category: "Intelligence",
    path: "/ZekuAI",
    inputs: ["text"],
    outputs: ["text"],
    defaultConfig: { prompt: "Write a poem about Kaspa" },
  },
  {
    id: "prompto",
    appName: "Prompto",
    label: "Prompto",
    sublabel: "Prompt Refiner",
    capability: "llm",
    icon: "Sparkles",
    color: "from-emerald-500 to-teal-500",
    desc: "Refine and improve a prompt",
    category: "Intelligence",
    path: "/Prompto",
    inputs: ["text"],
    outputs: ["text"],
    defaultConfig: { prompt: "Take this rough idea and turn it into a detailed image prompt: {{result}}" },
  },
  {
    id: "hercules",
    appName: "Hercules",
    label: "Hercules",
    sublabel: "Deep Research",
    capability: "research",
    icon: "Telescope",
    color: "from-blue-500 to-indigo-500",
    desc: "Live web research with real sources",
    category: "Intelligence",
    path: "/Hercules",
    inputs: ["text"],
    outputs: ["text"],
    defaultConfig: { topic: "Latest Kaspa ecosystem developments" },
  },
  {
    id: "browser",
    appName: "TTTV",
    label: "TTTV",
    sublabel: "Web Search",
    capability: "search",
    icon: "Search",
    color: "from-sky-500 to-cyan-500",
    desc: "Search the web for current information",
    category: "Intelligence",
    path: "/Browser",
    inputs: ["text"],
    outputs: ["text"],
    defaultConfig: { query: "Latest Kaspa news today" },
  },

  // ─── ACTIONS ───
  {
    id: "feed",
    appName: "TTT Feed",
    label: "TTT Feed",
    sublabel: "Post to Social",
    capability: "post",
    icon: "MessageSquarePlus",
    color: "from-fuchsia-500 to-pink-500",
    desc: "Post the result to the TTT social feed",
    category: "Action",
    path: "/Feed",
    inputs: ["text", "image"],
    outputs: ["confirmation"],
    defaultConfig: { author_name: "" },
  },
  {
    id: "fluxkmail",
    appName: "FluxKmail",
    label: "FluxKmail",
    sublabel: "Email Delivery",
    capability: "email",
    icon: "Mail",
    color: "from-orange-500 to-red-500",
    desc: "Email the result to a recipient",
    category: "Action",
    path: "/FluxKmail",
    inputs: ["text", "image"],
    outputs: ["confirmation"],
    defaultConfig: { to: "", subject: "MIRAGE Workflow", body: "{{result}}" },
  },
  {
    id: "x_post",
    appName: "X (Twitter)",
    label: "X",
    sublabel: "Tweet It",
    capability: "social",
    icon: "Twitter",
    color: "from-zinc-700 to-zinc-900",
    desc: "Open X compose with the result pre-filled",
    category: "Action",
    path: "/X",
    inputs: ["text"],
    outputs: ["confirmation"],
    defaultConfig: {},
  },
  {
    id: "ttt_feed_read",
    appName: "TTT Feed",
    label: "TTT Feed",
    sublabel: "Read Posts",
    capability: "read_feed",
    icon: "Rss",
    color: "from-rose-500 to-pink-500",
    desc: "Pull recent posts from TTT feed as input",
    category: "Source",
    path: "/Feed",
    inputs: [],
    outputs: ["text"],
    defaultConfig: { limit: 10, keyword: "" },
  },
];

export const MIRAGE_CATEGORIES = ["All", "Visual", "Intelligence", "Action", "Source"];

export const findTool = (id) => MIRAGE_TOOLS.find((t) => t.id === id);