import React, { useState } from 'react';
import { previewSdkSource, searchButtonExample } from '@/components/searchkaspa/searchPreviewSdk';

export default function SearchDeveloperExamples() {
  const [copied, setCopied] = useState('');
  const origin = window.location.origin;
  const request = `POST ${origin}/functions/searchKaspaApps\nContent-Type: application/json\n\n${JSON.stringify({ query: "Any builders working on a messaging platform?", natural_language: true, category: 'All', limit: 10 }, null, 2)}`;
  const usage = `import { createSearchKaspaClient } from './search-kaspa-preview.mjs';\nconst client = createSearchKaspaClient();\nconst result = await client.search('Who is building encrypted messaging?');\nfor (const match of result.results) {\n  console.log(match.name, match.url, match.match_evidence.quote);\n}`;
  const examples = [['HTTP request', request], ['JavaScript client', usage], ['Search Kaspa button', searchButtonExample(origin)]];
  const copy = async (label, text) => { try { await navigator.clipboard.writeText(text); setCopied(label); } catch { setCopied('Select and copy the example manually.'); } };
  const download = () => { const url = URL.createObjectURL(new Blob([previewSdkSource(origin)], { type: 'text/javascript' })); const a = document.createElement('a'); a.href = url; a.download = 'search-kaspa-preview.mjs'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <section id="integrate" className="space-y-5 scroll-mt-8">
    <div><p className="text-xs uppercase tracking-widest text-muted-foreground">Working preview · not the paid API</p><h2 className="mt-2 text-2xl font-semibold">Build against the search preview</h2></div>
    <p className="text-sm leading-7 text-muted-foreground">Use the published app’s domain in these examples, not a builder-preview address. Download the client from the published docs; it supports modern browsers and Node with native fetch. The link button opens Search Kaspa in a new tab—it is not an embedded search widget. No production SLA, KAS billing or API keys are available in this preview.</p>
    <button onClick={download} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Download preview client (.mjs)</button>
    {examples.map(([label, text]) => <article key={label} className="overflow-hidden rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><h3 className="text-sm font-medium">{label}</h3><button onClick={() => copy(label, text)} className="text-xs underline underline-offset-4">{copied === label ? 'Copied' : 'Copy'}</button></div><pre className="overflow-x-auto p-4 text-xs leading-6"><code>{text}</code></pre></article>)}
    <p role="status" className="text-xs text-muted-foreground">{copied && !examples.some(([label]) => label === copied) ? copied : ''}</p>
    <dl className="grid gap-4 text-sm sm:grid-cols-2">{[['query', '1–300 characters; send the original question, not rewritten keywords.'], ['natural_language', 'true selects grounded directory matching; false keeps legacy keyword search.'], ['category / limit', 'All by default; optional exact directory category. Limit 1–2000; grounded mode returns at most 20 matches.'], ['results', 'Existing directory records with original name/url and an exact match_evidence.quote. Render as text, never raw HTML.'], ['intent / evidence_status', 'Interpretation target and keywords; directory_only means these claims are not independently verified.'], ['coverage / no_match_reason', 'scanned and truncated describe index coverage. Empty results may mean missing evidence, not that nobody is building this.'], ['Errors and retries', '400 invalid input; 405 wrong method; 503 unavailable. Respect 429/Retry-After when supplied by hosting. Retry transient failures with bounded backoff.'], ['Version status', 'Experimental preview contract. Paid API, indexing SDK, embeddable widget and MCP adapter will need a separate versioned release.']].map(([name, description]) => <div key={name} className="border-t border-border pt-3"><dt className="font-mono text-xs">{name}</dt><dd className="mt-2 text-muted-foreground leading-6">{description}</dd></div>)}</dl>
  </section>;
}