import React from 'react';

const sections = [
  ['Public access, wallet identity', 'Planned: connect Scorpion / KCC20 without Google or an app-user login. A wallet address alone is not proof of ownership. Key issuance needs a fresh server challenge cryptographically bound to the wallet, or a uniquely bound on-chain proof verified from resolved inputs. No connect-only or signature-length fallback.'],
  ['One submitted request, one payment', 'Planned: issue an expiring invoice bound to the API key, operation, request hash, network, recipient and exact amount in sompi. The wallet approves the payment; the server verifies acceptance, payer attribution and the invoice binding before running the search or indexing task. Typing, suggestions and checking a receipt must not trigger another charge.'],
  ['Treasury and pricing', 'Planned: admins set a public receiving address and separate search/indexing fees. Only the receiving address is needed—never a treasury seed. The service fee goes to the treasury; the network fee goes to Kaspa miners and is estimated by the wallet. No production price or payment address is configured for Search Kaspa yet.'],
  ['Replay protection and retries', 'Required before launch: an atomic ledger must claim each payment output once across concurrent requests and invoices. A receipt must authorize only its original operation. Idempotent retries return the same job/result, not a new charge; failed paid jobs need a documented retry or credit policy. A transaction hash alone is not a bearer receipt.'],
  ['Keys, budgets and browser safety', 'Planned: wallet-bound, hashed, revocable keys with search/index scopes, expiry, usage history and limits. Secret keys stay in the integrator’s server or local client, never in a public button or HTML bundle. An API key grants service access, not permission to spend the wallet. Automated payments require a separately approved bounded spending mechanism; connecting Scorpion does not grant unlimited spending.'],
  ['Indexing does not buy credibility', 'Planned: paid submissions enter a validation queue. Verify source ownership/provenance, record evidence URLs and dates, block private-network fetches, and moderate spam. Payment does not guarantee acceptance, a verified badge or ranking. Claim-level citations and a correction process are still needed for independently verified builder results.'],
  ['MCP without Google', 'Not enabled: Base44’s built-in public MCP serves read-only entities, not paid function tools or custom API-key authentication. The proposed no-login route is a developer-side MCP adapter that calls the same paid HTTP API and returns a payment request for wallet approval. It must not expose unrelated TTT data or pass private keys to an AI client; its package and tool contract are not available yet.'],
];
export default function SearchDeveloperProtocol() {
  return <section id="payments" className="space-y-6 scroll-mt-8">
    <div><p className="text-xs uppercase tracking-widest text-muted-foreground">Design specification · not live</p><h2 className="mt-2 text-2xl font-semibold">Scorpion-paid Search Kaspa</h2><p className="mt-3 text-sm text-muted-foreground">The current preview does not charge KAS, issue API keys or enforce payment. Do not send funds to unlock this preview.</p></div>
    {sections.map(([title, text]) => <article key={title} className="border-t border-border pt-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></article>)}
    <p className="rounded-xl border border-border p-4 text-sm leading-6">Launch gates: real wallet proof, atomic settlement, admin pricing, key management, rate limits, payment-failure recovery, and closing all unmetered execution paths. Charging reduces abuse; it does not eliminate spam or denial-of-service attacks.</p>
  </section>;
}